"""CLF-C02 exam content for study app generator."""

LESSONS = [
    {
        "id": "1.1",
        "d": 0,
        "title": "Benefits of AWS Cloud",
        "icon": "ti-cloud",
        "points": [
            "☁️ Public cloud = rent a spot in AWS's giant shared playground instead of building your own — like using a community pool instead of digging one in your backyard.",
            "🚀 Deploy worldwide in minutes — pick a Region and go live fast, like opening a lemonade stand in any city overnight.",
            "🌍 Global reach — Regions and edge locations put your app close to users, like opening mini shops near your customers.",
            "📈 Elasticity — auto grow and shrink servers when traffic spikes, like adding extra cashiers only on busy Saturdays.",
            "⚡ Agility — try new ideas quickly without buying hardware, like testing recipes with borrowed kitchen tools.",
            "💰 Pay-as-you-go (OpEx) — no big upfront server purchases (CapEx); you only pay for what you use, like paying for electricity by the hour.",
        ],
    },
    {
        "id": "1.2",
        "d": 0,
        "title": "Well-Architected Framework",
        "icon": "ti-building-arch",
        "points": [
            "🏗️ Six pillars = six rules for building a sturdy cloud house: Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability.",
            "🔧 Operational Excellence — run and improve systems smoothly, like keeping a restaurant kitchen organized every night.",
            "🔒 Security — protect data with encryption, IAM, and monitoring, like locks, cameras, and ID badges.",
            "🛡️ Reliability — survive failures using multiple AZs, like having backup generators in two buildings.",
            "⚡ Performance Efficiency — use the right-sized tools for the job, like picking the right bike vs truck for delivery.",
            "💵 Cost Optimization — stop paying for unused stuff; rightsizing is like turning off lights in empty rooms.",
        ],
    },
    {
        "id": "1.3",
        "d": 0,
        "title": "Migration & Cloud Adoption (CAF)",
        "icon": "ti-truck-delivery",
        "points": [
            "🗺️ AWS CAF (Cloud Adoption Framework) — a roadmap with six perspectives: Business, People, Governance, Platform, Security, Operations.",
            "📦 Migration strategies — Rehost (lift-and-shift), Replatform, Refactor, Repurchase, Retire, Retain (the 6 R's).",
            "🚚 Snowball / Snowball Edge — ship a rugged box full of data when the internet is too slow, like mailing a moving truck of files.",
            "🔄 Database replication & DMS — copy databases to AWS with AWS Database Migration Service while apps keep running.",
            "🌱 CAF benefits — lower business risk, better ESG, more revenue, and smoother operations — like upgrading from a paper map to GPS.",
            "📋 Use AWS Migration Hub, Prescriptive Guidance, and partners to plan the journey step by step.",
        ],
    },
    {
        "id": "1.4",
        "d": 0,
        "title": "Cloud Economics",
        "icon": "ti-coin",
        "points": [
            "🏠 On-premises = you buy the house (fixed CapEx); cloud = you rent by the month (variable OpEx).",
            "📉 Economies of scale — AWS buys servers in huge bulk and passes savings to you, like a warehouse club for computers.",
            "📏 Rightsizing — pick instances that fit your actual need, not the biggest one 'just in case' — like wearing shoes that actually fit.",
            "🤖 Automation saves money — scripts replace manual work, like a robot vacuum instead of hiring someone daily.",
            "📜 BYOL vs included licenses — Bring Your Own License means you bring software licenses; included means AWS bundles them.",
            "💡 Cloud removes costs for power, cooling, and data-center building maintenance you would pay on-premises.",
        ],
    },
    {
        "id": "2.1",
        "d": 1,
        "title": "Shared Responsibility Model",
        "icon": "ti-shield-half",
        "points": [
            "🤝 Shared responsibility — AWS secures the cloud (hardware, hypervisor); you secure IN the cloud (data, apps, access).",
            "🏢 Security OF the cloud = AWS job: data centers, physical servers, and the global network.",
            "🔐 Security IN the cloud = your job: IAM users, security groups, encryption choices, and app patches on EC2.",
            "🗄️ RDS & Lambda — AWS patches more layers; you still manage data, permissions, and code.",
            "🖥️ EC2 — you patch the operating system; AWS manages the physical machine underneath.",
            "📊 Responsibility shifts up or down depending on how 'managed' the service is — more managed = AWS does more.",
        ],
    },
    {
        "id": "2.2",
        "d": 1,
        "title": "Security, Governance & Compliance",
        "icon": "ti-certificate",
        "points": [
            "📄 AWS Artifact — download compliance reports (SOC, PCI) like getting a health inspection certificate for the building.",
            "🔍 CloudTrail — records who called which API and when, like a security camera log for your account.",
            "📋 AWS Config — checks if resources follow rules (e.g., encrypted buckets), like a checklist inspector.",
            "🛡️ GuardDuty, Security Hub, Inspector — find threats, centralize findings, and scan for vulnerabilities.",
            "🔒 Encryption at rest (stored data) and in transit (moving data) — KMS, TLS/SSL via ACM.",
            "📊 Audit Manager — helps automate audit evidence collection for compliance frameworks.",
        ],
    },
    {
        "id": "2.3",
        "d": 1,
        "title": "IAM & Access Management",
        "icon": "ti-key",
        "points": [
            "👤 IAM — create users, groups, roles, and policies to control who can do what in AWS.",
            "🔑 Least privilege — give only the permissions needed, like giving a guest key to one room, not the whole building.",
            "🚫 Protect the root user — enable MFA, don't use it daily; only root can do a few special account tasks.",
            "🏢 IAM Identity Center (SSO) — one login for many AWS accounts and apps, like a school ID for every classroom.",
            "🎭 Roles — temporary credentials for services (Lambda, EC2) instead of hard-coded access keys in code.",
            "🔐 Secrets Manager & Systems Manager Parameter Store — safely store passwords and rotate them automatically.",
        ],
    },
    {
        "id": "2.4",
        "d": 1,
        "title": "Security Components & Resources",
        "icon": "ti-lock",
        "points": [
            "🧱 WAF — blocks web attacks like SQL injection at your app door.",
            "🛡️ Shield — DDoS protection; Standard is free for everyone.",
            "🔥 Network Firewall & Firewall Manager — VPC-level firewalls and centralized rule management.",
            "🏪 AWS Marketplace — buy third-party security tools alongside AWS services.",
            "📚 AWS Security Center, Knowledge Center, Security Blog — official help when something looks wrong.",
            "✅ Trusted Advisor — free basic checks (full set on Business Support) for security and cost best practices.",
        ],
    },
    {
        "id": "3.1",
        "d": 2,
        "title": "Deploy & Operate in AWS",
        "icon": "ti-code",
        "points": [
            "🖱️ AWS Management Console — click-and-go web UI, like a remote control for the cloud.",
            "⌨️ CLI & SDKs — script and automate with code; great for repeat tasks.",
            "📜 CloudFormation — Infrastructure as Code templates (JSON/YAML) to build the same setup every time.",
            "☁️ Deployment models — public (AWS shared cloud), private (your own data center), hybrid (mix of both).",
            "🔁 One-time manual tasks vs repeatable automated processes — automate when you will do it again.",
            "🌐 Access AWS via console, CLI, SDK, or APIs from anywhere with credentials.",
        ],
    },
    {
        "id": "3.2",
        "d": 2,
        "title": "Global Infrastructure",
        "icon": "ti-world",
        "points": [
            "🌎 Region — a geographic area (e.g., us-east-1); choose based on users, laws, and latency.",
            "🏢 Availability Zone (AZ) — isolated data centers within a Region; use multiple AZs for high availability.",
            "📍 Edge locations — CloudFront caches content close to users for faster delivery.",
            "🔄 Multi-AZ — if one data center fails, another keeps running — no shared single point of failure.",
            "🌍 Multi-Region — for disaster recovery, business continuity, or data sovereignty rules.",
            "⚡ HA (high availability) = spread across AZs; DR (disaster recovery) often uses another Region.",
        ],
    },
    {
        "id": "3.3",
        "d": 2,
        "title": "Compute Services",
        "icon": "ti-cpu",
        "points": [
            "🖥️ EC2 — virtual servers; instance families: compute-optimized, memory-optimized, storage-optimized, etc.",
            "💰 Pricing: On-Demand, Reserved/Savings Plans, Spot (cheap but interruptible), Dedicated Hosts.",
            "⚡ Lambda — run code without servers; pay per run, like paying per text message sent.",
            "📦 ECS & EKS — run Docker containers; Fargate runs containers without managing servers.",
            "📈 Auto Scaling — add/remove EC2 automatically when load changes.",
            "⚖️ Elastic Load Balancing — spread traffic across healthy instances in multiple AZs.",
        ],
    },
    {
        "id": "3.4",
        "d": 2,
        "title": "Database Services",
        "icon": "ti-database",
        "points": [
            "🗃️ RDS & Aurora — managed relational SQL databases with backups and Multi-AZ failover.",
            "⚡ DynamoDB — serverless NoSQL for huge scale and millisecond latency.",
            "🧠 ElastiCache — in-memory Redis/Memcached cache to speed up reads.",
            "📊 Redshift — data warehouse for big analytics SQL queries.",
            "🚚 DMS (Database Migration Service) — migrate databases to AWS with minimal downtime.",
            "🔧 SCT (Schema Conversion Tool) — convert database schemas (e.g., Oracle to PostgreSQL) for migration.",
        ],
    },
    {
        "id": "3.5",
        "d": 2,
        "title": "Network Services",
        "icon": "ti-network",
        "points": [
            "🏠 VPC — your private network in AWS with subnets, route tables, and gateways.",
            "🌐 Public subnet — routes to Internet Gateway; private subnet — no direct internet route.",
            "🔒 Security groups (stateful, instance level) and NACLs (stateless, subnet level).",
            "🗺️ Route 53 — DNS, domain registration, health checks, and failover routing.",
            "🔌 VPN & Direct Connect — private connections from your office to AWS.",
            "🌍 CloudFront — CDN that uses edge locations to cache content globally.",
        ],
    },
    {
        "id": "3.6",
        "d": 2,
        "title": "Storage Services",
        "icon": "ti-folder",
        "points": [
            "🪣 S3 — object storage for files, backups, and static websites; many storage classes (Standard, IA, Glacier).",
            "💾 EBS — block storage attached to one EC2 instance like a hard drive.",
            "📁 EFS — shared file storage (NFS) across many EC2 instances.",
            "🪟 FSx — managed Windows File Server or Lustre high-performance file systems.",
            "🌉 Storage Gateway — connect on-premises apps to AWS cloud storage seamlessly.",
            "🔄 S3 lifecycle policies move old data to cheaper tiers; AWS Backup centralizes backup across services.",
        ],
    },
    {
        "id": "3.7",
        "d": 2,
        "title": "AI/ML & Analytics",
        "icon": "ti-brain",
        "points": [
            "🤖 SageMaker — build, train, and deploy machine learning models.",
            "💬 Lex — chatbots that understand speech and text, like a phone menu that listens.",
            "🔎 Kendra — smart enterprise search that understands questions in plain language.",
            "📊 Athena — run SQL queries directly on S3 data without setting up a database.",
            "🌊 Kinesis — stream and process real-time data like live video views or click streams.",
            "🧩 Glue — ETL to prepare data; QuickSight — dashboards and business intelligence charts.",
        ],
    },
    {
        "id": "3.8",
        "d": 2,
        "title": "Other AWS Services",
        "icon": "ti-apps",
        "points": [
            "📨 SNS, SQS, EventBridge — notifications, queues, and event routing between apps.",
            "📞 Connect & SES — cloud call center and bulk/custom email sending.",
            "🛠️ CodeBuild, CodePipeline, X-Ray — build code, deploy pipelines, and trace app performance.",
            "🖥️ WorkSpaces, AppStream 2.0, WorkSpaces Secure Browser — virtual desktops and stream apps to users.",
            "📱 Amplify & AppSync — build mobile/web frontends and GraphQL APIs quickly.",
            "📡 IoT Core — connect and manage millions of devices like smart sensors.",
        ],
    },
    {
        "id": "4.1",
        "d": 3,
        "title": "Pricing Models",
        "icon": "ti-receipt",
        "points": [
            "💳 On-Demand — pay by the hour/second, no commitment; best for unpredictable workloads.",
            "📅 Reserved Instances & Savings Plans — big discounts for 1–3 year steady usage commitments.",
            "🎯 Spot Instances — up to 90% off spare capacity; can be interrupted — good for flexible batch jobs.",
            "🏠 Dedicated Hosts/Instances — physical isolation for licensing or compliance needs.",
            "📦 S3 storage classes — Standard (frequent access) to Glacier Deep Archive (cheapest, slow retrieval).",
            "🌐 Data transfer — inbound is often free; outbound and cross-Region transfer costs money.",
        ],
    },
    {
        "id": "4.2",
        "d": 3,
        "title": "Billing, Budget & Cost Management",
        "icon": "ti-chart-bar",
        "points": [
            "📊 Cost Explorer — charts of past and forecasted spending by service.",
            "🚨 AWS Budgets — email alerts when you hit spending thresholds.",
            "🧮 Pricing Calculator — estimate costs before you deploy anything.",
            "🏢 AWS Organizations — many accounts, one consolidated bill, and volume discounts.",
            "🏷️ Cost allocation tags — label resources (team, project) for detailed billing reports.",
            "📋 Cost and Usage Report (CUR) — detailed raw billing data export for finance teams.",
        ],
    },
    {
        "id": "4.3",
        "d": 3,
        "title": "Support & Resources",
        "icon": "ti-lifebuoy",
        "points": [
            "🆓 Basic Support — free docs, forums, Service Health Dashboard; no 24/7 phone support.",
            "👨‍💻 Developer Support — business-hours email; Business Support — 24/7 phone/chat + full Trusted Advisor.",
            "🏢 Enterprise & Enterprise On-Ramp — TAM (Technical Account Manager) and proactive guidance.",
            "💚 AWS Health Dashboard & Health API — personalized alerts about events affecting your resources.",
            "🤝 AWS Partner Network, Marketplace, Professional Services, and Solutions Architects for help.",
            "🛡️ Trust and Safety team — report abuse of AWS resources; re:Post and Knowledge Center for community answers.",
        ],
    },
]

QUESTIONS = [
    # ── 1.1 Benefits of AWS Cloud (6) ──
    {
        "d": 0, "t": "1.1",
        "q": "A student startup has $200 and needs to test an app idea without buying servers. Which core cloud benefit helps them avoid large upfront hardware costs?",
        "opts": ["Trade capital expense (CapEx) for variable operational expense (OpEx)", "Fault tolerance across Regions", "Dedicated physical hosts", "Perpetual free unlimited EC2"],
        "a": 0,
        "exp": "CapEx to OpEx means pay as you go instead of buying hardware upfront. Fault tolerance is about uptime, not upfront cost. Dedicated hosts are expensive. Free Tier helps but is not unlimited forever.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "An online store expects 10x normal traffic on Black Friday. They want servers to automatically add capacity during the spike and shrink afterward. Which cloud concept applies?",
        "opts": ["Elasticity", "Durability", "Data residency", "Colocation"],
        "a": 0,
        "exp": "Elasticity is automatic scale up and down with demand. Durability means data won't be lost. Data residency is where data legally lives. Colocation is renting data-center space, not auto-scaling.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "A company wants to shut down its on-premises data center and run everything on AWS shared infrastructure with no hardware to buy. Which deployment model is this?",
        "opts": ["Private cloud on company property", "Hybrid cloud", "Public cloud", "Community cloud"],
        "a": 2,
        "exp": "Public cloud means using AWS shared infrastructure with no owned hardware. Private cloud is on your own servers. Hybrid mixes on-prem and cloud. Community cloud is shared by organizations with common interests.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "A video startup needs to launch in three countries within one week. Their CEO cites 'speed of deployment' as the main AWS advantage. What enables this?",
        "opts": ["Pre-built global Regions and services ready on demand", "Shipping Snowball devices to each office", "Buying dedicated hosts in each country first", "Waiting 6 months for data-center construction"],
        "a": 0,
        "exp": "AWS Regions let you deploy globally in minutes without building data centers. Snowball is for data transfer, not launching apps. Dedicated hosts still deploy faster than building facilities but Regions are the key global speed advantage.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "Select TWO advantages of AWS global infrastructure that help a media company reach viewers worldwide.",
        "opts": ["Regions for deploying close to users", "Edge locations for caching content near viewers", "On-premises-only deployment", "Single Availability Zone for all users"],
        "a": [0, 1], "multi": True,
        "exp": "Regions place compute/storage geographically; edge locations (CloudFront) cache content close to users for low latency. On-premises-only misses cloud reach. One AZ is not global and lacks HA.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "A CFO asks why AWS can charge less per server than buying hardware. Which advantage explains this?",
        "opts": ["Economies of scale from massive shared purchasing", "Each customer gets isolated physical data centers", "AWS charges the same as retail hardware stores", "Long-term contracts are required for all services"],
        "a": 0,
        "exp": "Economies of scale: AWS buys at huge volume and passes savings on. Isolated data centers per customer would be enormously expensive. AWS is typically cheaper than DIY. Most services are pay-as-you-go.",
    },
    # ── 1.2 Well-Architected Framework (5) ──
    {
        "d": 0, "t": "1.2",
        "q": "An architect reviews a design and asks whether they are wasting money on oversized instances. Which Well-Architected pillar focuses on this?",
        "opts": ["Cost Optimization", "Security", "Operational Excellence", "Sustainability"],
        "a": 0,
        "exp": "Cost Optimization eliminates waste and right-sizes resources. Security protects systems. Operational Excellence improves operations. Sustainability focuses on environmental efficiency.",
    },
    {
        "d": 0, "t": "1.2",
        "q": "A payment system must recover quickly if an entire data center fails. Which pillar guides spreading workloads across multiple AZs?",
        "opts": ["Reliability", "Performance Efficiency", "Cost Optimization", "Sustainability"],
        "a": 0,
        "exp": "Reliability covers recovery from failures and meeting demand via multiple AZs. Performance Efficiency is about using resources efficiently for speed. Cost Optimization minimizes spend. Sustainability is environmental impact.",
    },
    {
        "d": 0, "t": "1.2",
        "q": "A security lead wants the architecture to follow least privilege, encryption, and threat detection. Which Well-Architected pillar is the primary focus?",
        "opts": ["Security", "Reliability", "Performance Efficiency", "Operational Excellence"],
        "a": 0,
        "exp": "The Security pillar covers identity, encryption, and detection. Reliability is uptime and recovery. Performance Efficiency is speed and right-sizing. Operational Excellence is day-to-day operations.",
    },
    {
        "d": 0, "t": "1.2",
        "q": "A team wants to reduce the environmental impact of their workloads by using fewer idle resources. Which Well-Architected pillar applies?",
        "opts": ["Sustainability", "Security", "Reliability", "Operational Excellence"],
        "a": 0,
        "exp": "Sustainability focuses on efficient resource use and reducing environmental impact. Security is protection. Reliability is uptime. Operational Excellence is running workloads well.",
    },
    {
        "d": 0, "t": "1.2",
        "q": "A SaaS product spreads web servers across two AZs behind a load balancer for 99.9% uptime. Which concept AND pillar align best?",
        "opts": ["High availability under the Reliability pillar", "Spot pricing under Cost Optimization", "Data warehousing under Performance Efficiency", "Batch processing under Operational Excellence"],
        "a": 0,
        "exp": "Multi-AZ plus load balancing is high availability, guided by the Reliability pillar. Spot pricing is a cost tactic. Data warehousing is analytics. Batch processing is offline job handling.",
    },
    # ── 1.3 Migration & CAF (5) ──
    {
        "d": 0, "t": "1.3",
        "q": "A factory has 80 TB of sensor logs and a 10 Mbps internet link. They need a one-time bulk transfer to S3. What should they use first?",
        "opts": ["AWS Snowball", "AWS Direct Connect", "Amazon CloudFront", "AWS DMS"],
        "a": 0,
        "exp": "Snowball is a physical device for large offline transfers when bandwidth is slow. Direct Connect is an ongoing private link, not a one-time appliance. CloudFront delivers content to users. DMS migrates databases, not bulk file shipping.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "A company lifts their on-premises VM unchanged into EC2 with no code changes. Which migration strategy is this?",
        "opts": ["Rehost (lift-and-shift)", "Refactor", "Repurchase", "Retire"],
        "a": 0,
        "exp": "Rehost moves workloads as-is to the cloud. Refactor rewrites for cloud-native. Repurchase moves to SaaS. Retire decommissions unused apps.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "Leadership wants reduced business risk and improved operational efficiency during cloud adoption. Which framework organizes these outcomes?",
        "opts": ["AWS Cloud Adoption Framework (CAF)", "AWS Well-Architected Tool only", "Amazon Macie", "AWS Shield"],
        "a": 0,
        "exp": "CAF provides perspectives and outcomes for cloud adoption including risk reduction and efficiency. Well-Architected reviews workload design. Macie finds PII. Shield is DDoS protection.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "An Oracle database must move to Amazon RDS PostgreSQL with schema conversion. Select TWO tools that help.",
        "opts": ["AWS Schema Conversion Tool (SCT)", "AWS Database Migration Service (DMS)", "AWS Snowball Edge only", "Amazon Cognito"],
        "a": [0, 1], "multi": True,
        "exp": "SCT converts schemas between engines; DMS replicates data during migration. Snowball Edge is offline data transfer/compute, not DB migration. Cognito handles user authentication.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "A team replatforms by moving from self-managed MySQL on EC2 to Amazon RDS with minor config changes but no app rewrite. Which strategy is this?",
        "opts": ["Replatform", "Rehost", "Retire", "Retain"],
        "a": 0,
        "exp": "Replatform makes small optimizations (managed DB) without full refactor. Rehost is unchanged lift-and-shift. Retire shuts down apps. Retain keeps them on-premises.",
    },
    # ── 1.4 Cloud Economics (5) ──
    {
        "d": 0, "t": "1.4",
        "q": "A finance team compares buying servers upfront versus paying AWS monthly. Which terms describe these cost models?",
        "opts": ["CapEx (on-premises purchase) vs OpEx (cloud pay-as-you-go)", "BYOL vs included license only", "Spot vs On-Demand only", "Reserved vs Savings Plans only"],
        "a": 0,
        "exp": "CapEx is upfront capital spending; OpEx is ongoing operational spending. BYOL is a licensing model. Spot/On-Demand and Reserved/Savings Plans are AWS pricing options within OpEx.",
    },
    {
        "d": 0, "t": "1.4",
        "q": "An admin discovers EC2 instances running at 5% CPU 24/7. Which cloud economics concept should they apply?",
        "opts": ["Rightsizing to smaller instances", "Adding more Regions", "Enabling GuardDuty", "Using Snowball"],
        "a": 0,
        "exp": "Rightsizing matches instance size to actual need, saving money. More Regions adds complexity and cost. GuardDuty detects threats. Snowball transfers data.",
    },
    {
        "d": 0, "t": "1.4",
        "q": "A software vendor brings existing Windows Server licenses to EC2 Dedicated Hosts instead of paying for included licenses. Which model is this?",
        "opts": ["Bring Your Own License (BYOL)", "Included license from AWS", "Spot Instance pricing", "Savings Plans"],
        "a": 0,
        "exp": "BYOL means you use licenses you already own on Dedicated Hosts. Included licenses bundle software cost into AWS pricing. Spot and Savings Plans are compute pricing models.",
    },
    {
        "d": 0, "t": "1.4",
        "q": "Select TWO on-premises costs that disappear or shrink when moving to AWS.",
        "opts": ["Data-center power and cooling", "Hardware maintenance contracts", "IAM user management", "S3 storage per GB"],
        "a": [0, 1], "multi": True,
        "exp": "Power, cooling, and hardware maintenance are physical data-center costs AWS absorbs. IAM management exists in both environments. S3 storage is a cloud cost, not an on-premises savings.",
    },
    {
        "d": 0, "t": "1.4",
        "q": "A ops team replaces manual server provisioning with CloudFormation templates. Which economic benefit does automation primarily provide?",
        "opts": ["Reduced labor cost and fewer human errors", "Free unlimited EC2 forever", "Automatic MFA for all users", "Elimination of all data transfer fees"],
        "a": 0,
        "exp": "Automation saves time and reduces mistakes, lowering operational cost. It does not make EC2 free, enable MFA, or remove data transfer charges.",
    },
    # ── 2.1 Shared Responsibility (5) ──
    {
        "d": 1, "t": "2.1",
        "q": "A new company asks who sets up IAM users and security groups on their EC2 servers. Under the shared responsibility model, who owns this?",
        "opts": ["AWS manages IAM for all customers automatically", "The customer is responsible for security IN the cloud", "A third-party auditor configures IAM", "AWS handles all security tasks in the account"],
        "a": 1,
        "exp": "Customers manage security IN the cloud: IAM, security groups, data. AWS secures the cloud platform (hardware, hypervisor). Auditors review compliance but don't run your account.",
    },
    {
        "d": 1, "t": "2.1",
        "q": "A team runs Amazon RDS for PostgreSQL. Who applies database engine patches and manages underlying server hardware?",
        "opts": ["Customer patches engine and physical servers", "AWS patches the engine and manages infrastructure; customer manages data and access", "Customer replaces failed hard drives", "AWS only provides the network"],
        "a": 1,
        "exp": "RDS is managed: AWS patches the engine and infrastructure. You control data, schemas, and access. Hard drives and physical hardware are AWS (OF the cloud).",
    },
    {
        "d": 1, "t": "2.1",
        "q": "A Lambda function processes S3 uploads. Who is responsible for patching the underlying operating system?",
        "opts": ["The customer patches the OS weekly", "AWS manages the OS and runtime infrastructure; customer manages function code and IAM", "Amazon Inspector patches Lambda automatically", "The customer replaces physical servers"],
        "a": 1,
        "exp": "Lambda is highly managed — AWS runs the infrastructure. You write code and set permissions. Inspector finds issues but doesn't patch Lambda OS. Physical servers are AWS's job.",
    },
    {
        "d": 1, "t": "2.1",
        "q": "Select TWO tasks that are AWS responsibilities under the shared responsibility model.",
        "opts": ["Physical data-center security", "Patching the EC2 guest operating system", "Hypervisor maintenance", "Encrypting S3 bucket policies"],
        "a": [0, 2], "multi": True,
        "exp": "AWS secures data centers and maintains the hypervisor (OF the cloud). Customers patch EC2 OS and configure S3 encryption/policies (IN the cloud).",
    },
    {
        "d": 1, "t": "2.1",
        "q": "A healthcare startup stores patient records in S3. Who is responsible for encryption settings and bucket access control?",
        "opts": ["AWS automatically encrypts all buckets without customer action", "The customer configures encryption and access policies", "AWS Artifact encrypts data", "GuardDuty manages S3 encryption"],
        "a": 1,
        "exp": "Customers own data protection IN the cloud. AWS provides encryption options but you configure them. Artifact provides compliance reports. GuardDuty detects threats.",
    },
    # ── 2.2 Security, Governance & Compliance (6) ──
    {
        "d": 1, "t": "2.2",
        "q": "An external auditor requests AWS SOC reports to prove cloud infrastructure compliance. Where can the company download these?",
        "opts": ["AWS Artifact", "Amazon CloudWatch", "AWS Cost Explorer", "AWS Marketplace"],
        "a": 0,
        "exp": "Artifact hosts compliance reports and agreements on demand. CloudWatch monitors metrics. Cost Explorer analyzes spend. Marketplace sells third-party software.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "After a critical S3 bucket was deleted, leadership needs to know which IAM user made the DeleteBucket call. Which service provides this?",
        "opts": ["AWS CloudTrail", "Amazon CloudWatch", "AWS Config", "AWS Trusted Advisor"],
        "a": 0,
        "exp": "CloudTrail logs API calls: who, when, what action. CloudWatch monitors metrics and app logs. Config tracks configuration changes. Trusted Advisor gives recommendations.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "A rule requires all S3 buckets to have encryption enabled. An admin creates an unencrypted bucket. Which service detects this drift?",
        "opts": ["AWS Config", "AWS CloudTrail", "AWS Artifact", "Amazon Inspector"],
        "a": 0,
        "exp": "Config evaluates resources against rules and records configuration history. CloudTrail logs API calls but doesn't continuously evaluate encryption. Artifact is compliance docs. Inspector scans EC2 vulnerabilities.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "Select TWO services that help with governance, auditing, and compliance monitoring.",
        "opts": ["AWS Audit Manager", "AWS CloudTrail", "Amazon CloudFront", "AWS Snowball"],
        "a": [0, 1], "multi": True,
        "exp": "Audit Manager automates audit evidence; CloudTrail logs API activity for auditing. CloudFront is a CDN. Snowball is physical data migration.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "At 2 AM, GuardDuty alerts show an EC2 instance mining cryptocurrency in a Region the company never uses. Which service generated this?",
        "opts": ["Amazon GuardDuty", "Amazon Inspector", "Amazon Macie", "AWS Artifact"],
        "a": 0,
        "exp": "GuardDuty detects threats and anomalies using ML on account activity. Inspector finds CVE vulnerabilities. Macie discovers PII in S3. Artifact hosts compliance PDFs.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "A security team wants one dashboard aggregating findings from GuardDuty, Inspector, and IAM Access Analyzer. Which service centralizes this?",
        "opts": ["AWS Security Hub", "AWS Artifact", "Amazon CloudFront", "AWS Budgets"],
        "a": 0,
        "exp": "Security Hub aggregates security findings from multiple AWS services. Artifact hosts compliance reports. CloudFront is CDN. Budgets tracks spending.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "A team must encrypt data while it travels between users and their website AND while stored on EBS volumes. Select TWO encryption types needed.",
        "opts": ["Encryption in transit (TLS/SSL)", "Encryption at rest (KMS for EBS)", "Edge location caching only", "Spot Instance pricing"],
        "a": [0, 1], "multi": True,
        "exp": "In-transit encryption protects moving data (HTTPS/TLS). At-rest encryption protects stored data (KMS with EBS). Edge caching and Spot pricing are unrelated to encryption.",
    },
    # ── 2.3 IAM & Access Management (5) ──
    {
        "d": 1, "t": "2.3",
        "q": "A new hire needs read-only access to one S3 bucket and must NOT launch EC2. Which principle should the admin follow?",
        "opts": ["Principle of least privilege", "Defense in depth for data centers", "Economies of scale", "Consolidated billing"],
        "a": 0,
        "exp": "Least privilege grants only minimum needed permissions. Defense in depth is layered security strategy. Economies of scale is pricing. Consolidated billing combines account bills.",
    },
    {
        "d": 1, "t": "2.3",
        "q": "A Lambda function must read DynamoDB without storing long-term access keys in code. What is the MOST secure approach?",
        "opts": ["Attach an IAM role to the Lambda function", "Embed IAM user access keys in the code", "Use the root account access keys", "Disable IAM and use public tables"],
        "a": 0,
        "exp": "IAM roles provide temporary credentials for AWS services. Embedding keys is insecure. Root keys are never acceptable. Public tables expose data.",
    },
    {
        "d": 1, "t": "2.3",
        "q": "A company with 50 AWS accounts wants employees to sign in once and access assigned accounts. Which service should they use?",
        "opts": ["AWS IAM Identity Center (AWS SSO)", "Amazon Cognito only", "AWS KMS", "Amazon Macie"],
        "a": 0,
        "exp": "IAM Identity Center provides SSO across AWS accounts and applications. Cognito is for customer-facing app auth. KMS manages keys. Macie finds PII in S3.",
    },
    {
        "d": 1, "t": "2.3",
        "q": "Select TWO best practices for protecting the AWS root user account.",
        "opts": ["Enable MFA on the root account", "Create an IAM admin user for daily tasks and lock away root credentials", "Share the root password with the team", "Create root access keys for automation"],
        "a": [0, 1], "multi": True,
        "exp": "MFA and avoiding daily root use protect the most powerful account. Sharing root credentials or creating root access keys are dangerous practices.",
    },
    {
        "d": 1, "t": "2.3",
        "q": "Select TWO places to securely store credentials with optional automatic rotation.",
        "opts": ["AWS Secrets Manager", "AWS Systems Manager Parameter Store (SecureString)", "Plain text in source code", "Public S3 bucket"],
        "a": [0, 1], "multi": True,
        "exp": "Secrets Manager and Parameter Store SecureString securely store credentials; Secrets Manager has built-in rotation. Plain text and public S3 are insecure.",
    },
    # ── 2.4 Security Components (5) ──
    {
        "d": 1, "t": "2.4",
        "q": "A public web app behind an ALB suffers SQL injection attempts. Which service should block these Layer 7 exploits?",
        "opts": ["AWS WAF", "AWS Shield Standard", "Amazon GuardDuty", "Security groups only"],
        "a": 0,
        "exp": "WAF blocks web application attacks like SQL injection. Shield protects against DDoS. GuardDuty detects account anomalies. Security groups control ports/IPs, not SQL patterns.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "A retail website experiences a large DDoS attack flooding network traffic. Which AWS service provides DDoS protection free at the basic level?",
        "opts": ["AWS Shield", "AWS WAF", "Amazon GuardDuty", "AWS Config"],
        "a": 0,
        "exp": "Shield Standard provides free DDoS protection for all customers. WAF blocks application-layer exploits. GuardDuty detects threats. Config tracks configurations.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "An enterprise needs IDS/IPS and domain filtering at the VPC network perimeter. Which managed service fits?",
        "opts": ["AWS Network Firewall", "Security groups only", "Amazon Macie", "AWS Certificate Manager"],
        "a": 0,
        "exp": "Network Firewall provides VPC-level IDS/IPS and domain filtering. Security groups are simpler instance firewalls. Macie scans S3. ACM manages SSL certificates.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "A security team wants a third-party firewall appliance deployed alongside AWS services. Where can they find it?",
        "opts": ["AWS Marketplace", "AWS Artifact", "AWS Cost Explorer", "Amazon S3 Glacier"],
        "a": 0,
        "exp": "Marketplace offers third-party security products. Artifact has compliance reports. Cost Explorer analyzes billing. Glacier is cold storage.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "A company manages WAF rules across 30 AWS accounts from one place. Which service helps centrally manage firewall rules?",
        "opts": ["AWS Firewall Manager", "Amazon Inspector", "AWS Cost Explorer", "Amazon Athena"],
        "a": 0,
        "exp": "Firewall Manager centrally administers WAF rules across accounts. Inspector scans vulnerabilities. Cost Explorer analyzes spend. Athena queries S3.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "Select TWO places to find official AWS security guidance and best practices.",
        "opts": ["AWS Security Blog", "AWS Knowledge Center", "Random forums only outside AWS", "Amazon Redshift query editor only"],
        "a": [0, 1], "multi": True,
        "exp": "AWS Security Blog and Knowledge Center are official AWS security resources. Random external forums aren't official. Redshift is a data warehouse, not a security docs site.",
    },
    # ── 3.1 Deploy & Operate (5) ──
    {
        "d": 2, "t": "3.1",
        "q": "A team deploys the same VPC, subnets, and EC2 setup to dev and prod using a reusable JSON template. Which service is this?",
        "opts": ["AWS CloudFormation", "Amazon CloudWatch", "AWS Cost Explorer", "Amazon Cognito"],
        "a": 0,
        "exp": "CloudFormation is Infrastructure as Code — repeatable templates. CloudWatch monitors metrics. Cost Explorer analyzes spend. Cognito handles app authentication.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "A developer automates nightly backups using a Python script calling AWS APIs. Which access methods are they using?",
        "opts": ["SDK/API programmatic access", "Only the Management Console", "Only Snowball", "Only Trusted Advisor"],
        "a": 0,
        "exp": "SDKs and APIs enable programmatic automation. Console is manual clicking. Snowball is physical transfer. Trusted Advisor gives recommendations.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "A manufacturer keeps factory data on-premises but bursts to AWS for product launches. Which deployment model is this?",
        "opts": ["Hybrid cloud", "Public cloud only", "Private cloud only", "Edge computing only"],
        "a": 0,
        "exp": "Hybrid combines on-premises with cloud resources. Public-only moves everything to AWS. Private-only stays on-prem. Edge computing is about proximity compute, not the main story here.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "Select TWO valid ways to access and manage AWS services.",
        "opts": ["AWS Management Console", "AWS CLI", "Only physical visits to data centers", "Only email to AWS Support for every action"],
        "a": [0, 1], "multi": True,
        "exp": "Console and CLI (plus SDKs/APIs) are standard access methods. You don't visit data centers to manage services. Support isn't how you operate resources daily.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "A bank built virtualized servers in its headquarters used only by the bank. Which deployment model is this?",
        "opts": ["Private cloud", "Public cloud", "Hybrid cloud", "Multi-cloud"],
        "a": 0,
        "exp": "Private cloud is dedicated infrastructure for one organization, usually on-premises. Public cloud is shared AWS. Hybrid mixes both. Multi-cloud uses multiple providers.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "A team manages 500 Linux EC2 instances and must apply security patches on a schedule from a central console. Which service helps?",
        "opts": ["AWS Systems Manager", "Amazon CloudFront", "Amazon Macie", "AWS Certificate Manager"],
        "a": 0,
        "exp": "Systems Manager (Patch Manager) automates patching and ops tasks at scale on EC2. CloudFront is CDN. Macie finds PII in S3. ACM manages SSL certs.",
    },
    # ── 3.2 Global Infrastructure (5) ──
    {
        "d": 2, "t": "3.2",
        "q": "A video startup has most users in Europe and must keep data in Europe. What should they do first?",
        "opts": ["Choose a European Region and deploy across multiple AZs there", "Deploy in one AZ in any Region worldwide", "Use only Edge Locations instead of Regions", "Connect Direct Connect before choosing a Region"],
        "a": 0,
        "exp": "Pick a European Region for data residency and latency; use multiple AZs for HA. One AZ anywhere misses both. Edge Locations cache but don't replace Regional deployment. Direct Connect doesn't choose geography.",
    },
    {
        "d": 2, "t": "3.2",
        "q": "An e-commerce site must stay online if one data center has a power failure in us-east-1. What is the BEST HA step?",
        "opts": ["Deploy across multiple Availability Zones in us-east-1", "Run everything in one AZ with a larger instance", "Copy the app to every Region worldwide", "Use Spot Instances in one AZ"],
        "a": 0,
        "exp": "Multiple AZs provide HA within a Region. One AZ is a single point of failure. All Regions is costly overkill for many apps. Spot can be interrupted.",
    },
    {
        "d": 2, "t": "3.2",
        "q": "A news site serves static images globally with slow loads in Asia. Which feature addresses this WITHOUT moving the origin?",
        "opts": ["Amazon CloudFront edge locations", "AWS Snowball to each country", "Amazon EBS on user devices", "Direct Connect from every home"],
        "a": 0,
        "exp": "CloudFront caches at edge locations worldwide. Snowball is migration, not delivery. EBS is EC2 block storage. Direct Connect is a business network link.",
    },
    {
        "d": 2, "t": "3.2",
        "q": "Select TWO reasons a company would deploy workloads in multiple AWS Regions.",
        "opts": ["Disaster recovery and business continuity", "Data sovereignty and low latency for distant users", "Because AZs share a single point of failure", "To avoid using any Availability Zones"],
        "a": [0, 1], "multi": True,
        "exp": "Multi-Region supports DR, compliance/data sovereignty, and global latency. AZs are designed NOT to share single points of failure. You still use AZs within each Region.",
    },
    {
        "d": 2, "t": "3.2",
        "q": "A design keeps serving traffic when one server crashes because others pick up the work. Which term describes this?",
        "opts": ["Fault tolerance", "Agility", "CapEx", "Edge caching"],
        "a": 0,
        "exp": "Fault tolerance means the system continues when components fail. Agility is fast resource deployment. CapEx is upfront spending. Edge caching is CDN-related.",
    },
    # ── 3.3 Compute (6) ──
    {
        "d": 2, "t": "3.3",
        "q": "A startup's web traffic is unpredictable with no long-term commitment. Which EC2 pricing model fits best?",
        "opts": ["On-Demand Instances", "Reserved Instances", "Spot Instances for production web without handling interrupts", "Dedicated Hosts"],
        "a": 0,
        "exp": "On-Demand has no commitment for unpredictable workloads. Reserved needs commitment. Spot can be interrupted — risky for unpredictable production without design. Dedicated Hosts are for isolation/licensing.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "Every time a user uploads a photo to S3, a script creates a thumbnail within seconds then stops. Which compute service fits?",
        "opts": ["AWS Lambda", "Amazon EC2 always running", "Amazon Redshift", "AWS Direct Connect"],
        "a": 0,
        "exp": "Lambda runs event-driven code (S3 trigger) and charges per execution. Always-on EC2 costs while idle. Redshift is analytics. Direct Connect is a network link.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "Select TWO AWS services that let you run containers without managing EC2 servers directly.",
        "opts": ["Amazon ECS on AWS Fargate", "Amazon EKS on AWS Fargate", "Amazon EC2 with manual Docker only", "Amazon Redshift"],
        "a": [0, 1], "multi": True,
        "exp": "Both ECS and EKS can use Fargate to run containers serverlessly. EC2 with manual Docker requires you to manage servers. Redshift is a data warehouse.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "A media company renders thousands of videos overnight; jobs can restart if interrupted. Which pricing model is MOST appropriate?",
        "opts": ["Spot Instances", "On-Demand Instances", "Dedicated Hosts", "Reserved Instances with no flexibility"],
        "a": 0,
        "exp": "Spot offers up to 90% off for fault-tolerant batch work that can restart. On-Demand costs more. Dedicated Hosts are for licensing. Reserved suits steady always-on workloads.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "When website traffic increases, new EC2 instances launch automatically; when it drops, extras terminate. Which service provides this?",
        "opts": ["AWS Auto Scaling", "Amazon SNS", "AWS CloudFormation", "Amazon Athena"],
        "a": 0,
        "exp": "Auto Scaling adjusts EC2 capacity based on policies. SNS sends notifications. CloudFormation deploys templates. Athena queries S3 with SQL.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "Traffic must spread evenly across six EC2 instances in multiple AZs based on HTTP requests. Which service performs this?",
        "opts": ["Elastic Load Balancing (Application Load Balancer)", "Amazon CloudFront origin only", "Route 53 domain registration only", "AWS Direct Connect"],
        "a": 0,
        "exp": "ALB distributes HTTP traffic across targets in multiple AZs. CloudFront caches at edge. Route 53 is DNS. Direct Connect is private networking.",
    },
    # ── 3.4 Databases (5) ──
    {
        "d": 2, "t": "3.4",
        "q": "A team needs managed MySQL with automated backups and Multi-AZ failover without managing the OS. Which service fits?",
        "opts": ["Amazon RDS", "Amazon DynamoDB", "Amazon Redshift", "Amazon ElastiCache"],
        "a": 0,
        "exp": "RDS provides managed relational databases with backups and Multi-AZ. DynamoDB is NoSQL. Redshift is a warehouse. ElastiCache is in-memory cache.",
    },
    {
        "d": 2, "t": "3.4",
        "q": "A mobile game needs millions of leaderboard updates per second with single-digit millisecond latency. Which service fits?",
        "opts": ["Amazon DynamoDB", "Amazon RDS MySQL", "Amazon Redshift", "Amazon EFS"],
        "a": 0,
        "exp": "DynamoDB is serverless NoSQL built for massive scale and low latency. RDS requires capacity planning. Redshift is analytics. EFS is file storage.",
    },
    {
        "d": 2, "t": "3.4",
        "q": "A news site loads the same article thousands of times per minute. They want an in-memory layer to reduce DB load. Which service?",
        "opts": ["Amazon ElastiCache", "Amazon S3 Glacier", "AWS Snowball", "Amazon Route 53"],
        "a": 0,
        "exp": "ElastiCache (Redis/Memcached) caches frequently read data in memory. Glacier is cold archive. Snowball is physical migration. Route 53 is DNS.",
    },
    {
        "d": 2, "t": "3.4",
        "q": "An on-premises PostgreSQL database must replicate to AWS with minimal downtime during cutover. Which service helps?",
        "opts": ["AWS Database Migration Service (DMS)", "AWS Schema Conversion Tool only", "Amazon S3 lifecycle policies", "AWS Snowball Edge"],
        "a": 0,
        "exp": "DMS replicates databases to AWS during migration. SCT converts schemas but doesn't replicate ongoing data alone. S3 lifecycle manages object tiers. Snowball Edge is offline transfer.",
    },
    {
        "d": 2, "t": "3.4",
        "q": "Select TWO database types and their matching AWS services.",
        "opts": ["Relational — Amazon Aurora", "NoSQL key-value — Amazon DynamoDB", "In-memory cache — Amazon Redshift only", "Data warehouse — Amazon DynamoDB only"],
        "a": [0, 1], "multi": True,
        "exp": "Aurora is relational; DynamoDB is NoSQL. ElastiCache (not Redshift) is in-memory cache. Redshift is the data warehouse, not DynamoDB.",
    },
    # ── 3.5 Network (5) ──
    {
        "d": 2, "t": "3.5",
        "q": "An architect places web servers in subnets with Internet Gateway routes and databases in subnets without direct internet. Which pattern is this?",
        "opts": ["Public subnets for web, private subnets for database", "Private subnets for web, public for database", "All resources in default VPC with one SG", "Edge Locations as database subnets"],
        "a": 0,
        "exp": "Public subnets route to IGW; private subnets don't expose databases directly. Reversing tiers exposes databases. Edge Locations aren't VPC subnets.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "A company owns myapp.com and needs DNS failover routing when one endpoint is unhealthy. Which service provides this?",
        "opts": ["Amazon Route 53", "Amazon CloudWatch", "AWS CloudTrail", "Amazon Inspector"],
        "a": 0,
        "exp": "Route 53 is DNS with health checks and failover policies. CloudWatch monitors metrics. CloudTrail logs API calls. Inspector scans vulnerabilities.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "An enterprise needs a consistent private dedicated network from their office to AWS with lower latency than the public internet. Which service?",
        "opts": ["AWS Direct Connect", "AWS Snowball", "Amazon CloudFront", "S3 Transfer Acceleration only"],
        "a": 0,
        "exp": "Direct Connect is a dedicated private line to AWS. Snowball is physical migration. CloudFront is CDN. Transfer Acceleration speeds public internet uploads.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "A security team must block a malicious IP range at the subnet boundary with explicit DENY rules. Which tool supports this?",
        "opts": ["Network ACL (NACL)", "Security group on each instance", "AWS Certificate Manager", "Amazon Cognito"],
        "a": 0,
        "exp": "NACLs are stateless subnet firewalls with allow AND deny rules. Security groups only allow (implicit deny) at instance level. ACM manages certs. Cognito handles app sign-in.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "Select TWO ways to connect an on-premises network to AWS privately.",
        "opts": ["AWS Site-to-Site VPN", "AWS Direct Connect", "Amazon CloudFront distribution", "Amazon S3 bucket policy"],
        "a": [0, 1], "multi": True,
        "exp": "VPN and Direct Connect connect on-premises to AWS privately. CloudFront delivers content to end users. S3 bucket policies control object access, not network connectivity.",
    },
    # ── 3.6 Storage (6) ──
    {
        "d": 2, "t": "3.6",
        "q": "A marketing site stores millions of images retrievable via HTTP at unlimited scale. Which storage service fits?",
        "opts": ["Amazon S3", "Amazon EBS", "Amazon EFS", "Amazon ElastiCache"],
        "a": 0,
        "exp": "S3 is object storage at unlimited scale with HTTP access. EBS is block storage for one EC2. EFS is shared files. ElastiCache is memory cache.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "Ten EC2 web servers must read and write the same config files using a POSIX file system. Which storage supports this?",
        "opts": ["Amazon EFS", "Amazon EBS", "Amazon S3 Standard", "Amazon DynamoDB"],
        "a": 0,
        "exp": "EFS is managed NFS shared across many EC2 instances. EBS typically mounts to one instance. S3 is object storage, not POSIX. DynamoDB is a database.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "A law firm must keep email archives 7 years, rarely accessed, lowest cost, retrieval up to 12 hours. Which S3 class fits?",
        "opts": ["S3 Glacier Deep Archive", "S3 Standard", "Amazon EBS gp3", "Amazon EFS One Zone"],
        "a": 0,
        "exp": "Glacier Deep Archive is lowest-cost long-term archive with hours retrieval. Standard is frequent access. EBS and EFS are active compute storage.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "A Windows shop needs a managed Windows File Server in AWS for SMB shares. Which service should they use?",
        "opts": ["Amazon FSx for Windows File Server", "Amazon EFS only", "Amazon S3 Glacier", "AWS Storage Gateway only"],
        "a": 0,
        "exp": "FSx for Windows provides managed SMB file shares. EFS is Linux NFS. Glacier is archive storage. Storage Gateway connects on-prem to cloud but FSx is the managed Windows files answer.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "An on-premises application must access S3 as if it were local storage with cached frequently used files. Which service helps?",
        "opts": ["AWS Storage Gateway", "Amazon EBS Multi-Attach", "Amazon CloudFront only", "AWS Snowball for daily access"],
        "a": 0,
        "exp": "Storage Gateway bridges on-premises apps to AWS cloud storage with caching. EBS Multi-Attach shares block storage. CloudFront is CDN. Snowball isn't for daily file access.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "Select TWO services that help with backup management across AWS resources.",
        "opts": ["AWS Backup", "S3 lifecycle policies to cheaper tiers", "Amazon Cognito user pools", "AWS WAF"],
        "a": [0, 1], "multi": True,
        "exp": "AWS Backup centralizes backups; S3 lifecycle moves data to cheaper storage classes over time. Cognito is authentication. WAF is web firewall.",
    },
    # ── 3.7 AI/ML & Analytics (6) ──
    {
        "d": 2, "t": "3.7",
        "q": "A data science team needs to build, train, and deploy machine learning models without managing infrastructure. Which service?",
        "opts": ["Amazon SageMaker", "Amazon Lex", "Amazon Kendra", "Amazon Connect"],
        "a": 0,
        "exp": "SageMaker is the ML platform for building and deploying models. Lex is chatbots. Kendra is enterprise search. Connect is a cloud contact center.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "A bank wants a phone chatbot that understands customer speech for balance inquiries. Which service fits?",
        "opts": ["Amazon Lex", "Amazon Athena", "Amazon Kinesis", "AWS Glue"],
        "a": 0,
        "exp": "Lex builds conversational chatbots with speech and text. Athena queries S3 with SQL. Kinesis streams data. Glue is ETL.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "Employees ask natural-language questions across internal PDFs and wikis. Which service provides intelligent search?",
        "opts": ["Amazon Kendra", "Amazon QuickSight", "Amazon SES", "AWS X-Ray"],
        "a": 0,
        "exp": "Kendra is ML-powered enterprise search. QuickSight is BI dashboards. SES sends email. X-Ray traces application performance.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "An analyst needs to run SQL queries on log files in S3 without provisioning a database server. Which service?",
        "opts": ["Amazon Athena", "Amazon RDS", "Amazon DynamoDB", "Amazon ElastiCache"],
        "a": 0,
        "exp": "Athena runs serverless SQL directly on S3 data. RDS and DynamoDB require database infrastructure. ElastiCache is cache.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "Select TWO analytics services: one for SQL on S3 without a server, one for streaming real-time data.",
        "opts": ["Amazon Athena (SQL on S3)", "Amazon Kinesis (streaming data)", "Amazon Lex (chatbot)", "AWS Shield (DDoS)"],
        "a": [0, 1], "multi": True,
        "exp": "Athena queries S3 with SQL serverlessly. Kinesis ingests real-time streams. Lex is conversational AI. Shield is DDoS protection.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "Select TWO services used together for analytics: one prepares/transforms data, one creates dashboards.",
        "opts": ["AWS Glue (ETL)", "Amazon QuickSight (BI dashboards)", "Amazon Lex (chatbot)", "AWS Shield (DDoS)"],
        "a": [0, 1], "multi": True,
        "exp": "Glue prepares data; QuickSight builds dashboards. Lex is conversational AI. Shield is DDoS protection.",
    },
    # ── 3.8 Other Services (6) ──
    {
        "d": 2, "t": "3.8",
        "q": "A microservices app needs to decouple order processing so one slow service doesn't block others. Which service queues messages?",
        "opts": ["Amazon SQS", "Amazon SNS fan-out only without queues", "Amazon Route 53", "Amazon EBS"],
        "a": 0,
        "exp": "SQS is a managed message queue for decoupling. SNS is pub/sub notifications (often paired with SQS). Route 53 is DNS. EBS is block storage.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "When an EC2 instance stops, an email alert and a Lambda function must run automatically. Which service routes events?",
        "opts": ["Amazon EventBridge", "Amazon SQS only", "Amazon EFS", "AWS Direct Connect"],
        "a": 0,
        "exp": "EventBridge routes events from AWS services to targets like Lambda and SNS/email. SQS queues messages but doesn't route EC2 state change events natively. EFS is storage. Direct Connect is networking.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A contact center wants cloud-based phone support with agents working from home. Which service fits?",
        "opts": ["Amazon Connect", "Amazon SES", "AWS CodePipeline", "Amazon AppStream 2.0"],
        "a": 0,
        "exp": "Connect is a cloud contact center. SES sends email. CodePipeline is CI/CD. AppStream streams desktop applications.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A mobile team wants to build a web and iOS app frontend with hosted backend quickly. Which service helps?",
        "opts": ["AWS Amplify", "AWS IoT Core", "Amazon Redshift", "AWS Snowball"],
        "a": 0,
        "exp": "Amplify builds and deploys full-stack web/mobile apps. IoT Core manages devices. Redshift is analytics. Snowball is data transfer.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "Select TWO developer tools for building, deploying, and troubleshooting applications.",
        "opts": ["AWS CodePipeline", "AWS X-Ray", "Amazon Connect", "Amazon SES"],
        "a": [0, 1], "multi": True,
        "exp": "CodePipeline automates CI/CD; X-Ray traces requests for debugging. Connect is call center. SES is email.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A factory connects 10,000 temperature sensors sending data to the cloud for monitoring. Which service manages these devices?",
        "opts": ["AWS IoT Core", "Amazon SQS", "Amazon WorkSpaces", "AWS AppSync"],
        "a": 0,
        "exp": "IoT Core connects and manages IoT devices at scale. SQS queues messages. WorkSpaces is virtual desktops. AppSync is GraphQL API.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "Remote contractors need a full Windows desktop in the browser without a company laptop. Which service provides virtual desktops?",
        "opts": ["Amazon WorkSpaces", "Amazon AppStream 2.0", "AWS Amplify", "Amazon SES"],
        "a": 0,
        "exp": "WorkSpaces provides persistent virtual desktops (DaaS). AppStream streams individual applications. Amplify builds apps. SES sends email.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A CAD vendor wants customers to stream a heavy 3D app from the browser without installing it locally. Which service fits?",
        "opts": ["Amazon AppStream 2.0", "Amazon WorkSpaces", "Amazon Connect", "AWS IoT Core"],
        "a": 0,
        "exp": "AppStream 2.0 streams desktop applications to browsers. WorkSpaces is full virtual desktops. Connect is call center. IoT Core manages devices.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A mobile app needs a managed GraphQL API backend that syncs offline data. Which service should the team use?",
        "opts": ["AWS AppSync", "Amazon SNS", "Amazon Redshift", "AWS Snowball"],
        "a": 0,
        "exp": "AppSync is a managed GraphQL API with real-time and offline sync. SNS sends notifications. Redshift is analytics. Snowball transfers data.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A marketing platform sends millions of transactional order-confirmation emails. Which service handles bulk and transactional email?",
        "opts": ["Amazon SES", "Amazon SNS", "Amazon Connect", "AWS X-Ray"],
        "a": 0,
        "exp": "SES (Simple Email Service) sends bulk and transactional email. SNS is pub/sub notifications (not email delivery at scale). Connect is call center. X-Ray traces apps.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "A dev team needs a managed service to compile source code and run unit tests on every git push. Which service fits?",
        "opts": ["AWS CodeBuild", "AWS CodePipeline only without build steps", "Amazon QuickSight", "Amazon Kendra"],
        "a": 0,
        "exp": "CodeBuild compiles code and runs tests. CodePipeline orchestrates the pipeline but CodeBuild does the actual build work. QuickSight is BI. Kendra is search.",
    },
    # ── 4.1 Pricing Models (5) ──
    {
        "d": 3, "t": "4.1",
        "q": "A company runs 24/7 payroll on EC2 unchanged for three years. They want the largest discount with commitment. Which option?",
        "opts": ["Reserved Instances or Savings Plans", "Spot Instances", "On-Demand only", "AWS Snowball"],
        "a": 0,
        "exp": "Reserved/Savings Plans offer up to ~72% off for 1–3 year steady usage. Spot is interruptible. On-Demand is flexible but expensive. Snowball is data transfer.",
    },
    {
        "d": 3, "t": "4.1",
        "q": "A software vendor must run EC2 on a specific physical server for per-socket license compliance. Which option?",
        "opts": ["Dedicated Hosts", "Spot Fleet only", "AWS Lambda", "S3 Intelligent-Tiering"],
        "a": 0,
        "exp": "Dedicated Hosts provide physical servers for license compliance. Spot uses spare capacity that can move. Lambda is serverless. Intelligent-Tiering automates S3 storage class.",
    },
    {
        "d": 3, "t": "4.1",
        "q": "A team frequently transfers large datasets from EC2 in us-east-1 to S3 in eu-west-1. Which cost should they expect?",
        "opts": ["Outbound cross-Region data transfer charges", "Free unlimited cross-Region transfer always", "Inbound transfer fees from internet only", "No charges for any S3 operations"],
        "a": 0,
        "exp": "Cross-Region data transfer out incurs charges. Inbound from internet to AWS is often free. S3 operations and storage have their own pricing.",
    },
    {
        "d": 3, "t": "4.1",
        "q": "Select TWO compute purchasing options suitable for fault-tolerant batch rendering that can restart.",
        "opts": ["Spot Instances", "Savings Plans with steady usage", "Spot Fleet for scalable batch", "Dedicated Hosts for license isolation only"],
        "a": [0, 2], "multi": True,
        "exp": "Spot and Spot Fleet suit interruptible batch work at low cost. Savings Plans need steady commitment. Dedicated Hosts are for licensing, not cheapest batch.",
    },
    {
        "d": 3, "t": "4.1",
        "q": "A photo archive is accessed once a year but must stay durable. Which S3 storage class balances low cost and retrieval time of hours?",
        "opts": ["S3 Glacier Flexible Retrieval or Glacier Deep Archive", "S3 Standard", "EBS io2 volumes", "EFS Standard"],
        "a": 0,
        "exp": "Glacier classes are for rare access at low cost with hours retrieval. Standard is frequent access. EBS and EFS are for active compute workloads.",
    },
    # ── 4.2 Billing & Cost Management (6) ──
    {
        "d": 3, "t": "4.2",
        "q": "A finance team wants charts of EC2 vs S3 spending over six months with month-over-month trends. Which tool?",
        "opts": ["AWS Cost Explorer", "AWS Budgets", "AWS Pricing Calculator", "AWS Artifact"],
        "a": 0,
        "exp": "Cost Explorer visualizes past and forecasted spending. Budgets sends threshold alerts. Pricing Calculator estimates future costs. Artifact provides compliance reports.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "A startup wants email alerts at 80% and 100% of their $1,000 monthly limit. Which service should they configure?",
        "opts": ["AWS Budgets", "AWS Cost Explorer", "AWS Pricing Calculator", "CloudWatch Logs only"],
        "a": 0,
        "exp": "Budgets sets cost thresholds and notifications. Cost Explorer analyzes history. Pricing Calculator estimates pre-deployment. CloudWatch Logs stores application logs.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "Before building a three-tier architecture, an architect estimates monthly costs for EC2, RDS, and S3. Which tool?",
        "opts": ["AWS Pricing Calculator", "AWS Cost Explorer", "AWS Budgets", "AWS Trusted Advisor"],
        "a": 0,
        "exp": "Pricing Calculator estimates costs before deployment. Cost Explorer reviews actual bills. Budgets alerts on thresholds. Trusted Advisor recommends optimizations.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "A company with 20 AWS accounts wants one combined invoice and volume discounts. Which service enables this?",
        "opts": ["AWS Organizations with consolidated billing", "AWS Budgets in each account separately", "CloudWatch cross-account dashboards only", "AWS Artifact only"],
        "a": 0,
        "exp": "Organizations consolidates billing under a management account. Budgets alerts per account but doesn't merge invoices. CloudWatch monitors metrics. Artifact is compliance.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "Finance needs detailed raw billing data exported hourly to analyze with their own tools. Which report should they enable?",
        "opts": ["AWS Cost and Usage Report (CUR)", "AWS Artifact SOC report", "Trusted Advisor check", "Route 53 health check"],
        "a": 0,
        "exp": "CUR provides granular billing line items for analysis. Artifact has compliance docs. Trusted Advisor gives recommendations. Route 53 health checks monitor endpoints.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "Select TWO ways to track which team spent what in a shared AWS account.",
        "opts": ["Cost allocation tags on resources", "AWS Cost Explorer filtered by tags", "Disabling CloudTrail", "Removing all IAM users"],
        "a": [0, 1], "multi": True,
        "exp": "Tags label resources; Cost Explorer breaks down spend by tag. Disabling CloudTrail hurts auditing. Removing IAM users breaks access control.",
    },
    # ── 4.3 Support & Resources (5) ──
    {
        "d": 3, "t": "4.3",
        "q": "A solo developer needs business-hours email support but NOT 24/7 phone support. Which plan fits?",
        "opts": ["Developer Support", "Basic Support", "Business Support", "Enterprise Support"],
        "a": 0,
        "exp": "Developer Support adds business-hours email. Basic has no technical support cases. Business adds 24/7 phone/chat. Enterprise adds a TAM.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "Select TWO differences between Basic Support and Business Support.",
        "opts": ["Business includes 24/7 phone and chat support", "Business includes full Trusted Advisor checks", "Basic includes a dedicated TAM", "Basic includes 24/7 Cloud Support Engineers"],
        "a": [0, 1], "multi": True,
        "exp": "Business Support adds 24/7 phone/chat and full Trusted Advisor. Basic has no 24/7 technical support and no TAM. TAM comes with Enterprise Support.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "A global bank wants a dedicated Technical Account Manager (TAM) for proactive architecture reviews. Which plan includes a TAM?",
        "opts": ["Enterprise Support", "Business Support", "Developer Support", "Basic Support"],
        "a": 0,
        "exp": "Enterprise Support includes a dedicated TAM. Business has 24/7 support but no assigned TAM. Developer and Basic do not include TAM.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "Operations wants programmatic alerts about AWS events affecting their resources (e.g., scheduled maintenance). Which tool?",
        "opts": ["AWS Health API / AWS Health Dashboard", "AWS Cost Explorer", "Amazon Macie", "AWS Snowball"],
        "a": 0,
        "exp": "Health Dashboard and Health API provide personalized service event alerts. Cost Explorer is billing. Macie finds PII. Snowball transfers data.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "Select TWO resources for getting official AWS technical help and documentation.",
        "opts": ["AWS Knowledge Center", "AWS re:Post community", "Unofficial third-party wikis only", "Reporting abuse to Trust and Safety for how-to guides"],
        "a": [0, 1], "multi": True,
        "exp": "Knowledge Center and re:Post are official AWS help resources. Unofficial wikis aren't authoritative. Trust and Safety handles abuse reports, not documentation.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "A large enterprise is not ready for full Enterprise Support but wants a subset including a pool of TAM access. Which plan fits?",
        "opts": ["Enterprise On-Ramp Support", "Basic Support", "Developer Support only", "AWS Budgets"],
        "a": 0,
        "exp": "Enterprise On-Ramp bridges Business and Enterprise with pooled TAM access. Basic and Developer lack TAM. Budgets is a cost alert tool.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "Someone discovers AWS resources being used for phishing and spam. Which team should they contact to report abuse?",
        "opts": ["AWS Trust and Safety team", "AWS Professional Services", "Amazon Redshift support", "AWS Pricing Calculator team"],
        "a": 0,
        "exp": "Trust and Safety investigates abuse of AWS resources. Professional Services helps with projects. Redshift is a database. Pricing Calculator estimates costs.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "A company planning a large migration wants AWS experts to help design and execute the move. Which option provides this?",
        "opts": ["AWS Professional Services", "AWS Artifact compliance downloads", "Amazon Macie", "AWS Snowball only"],
        "a": 0,
        "exp": "Professional Services provides paid expert migration and architecture help. Artifact has compliance docs. Macie finds PII. Snowball is a transfer device, not consulting.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "Select TWO benefits available to members of the AWS Partner Network (APN).",
        "opts": ["Partner training and certification", "Partner events and volume discounts", "Free unlimited EC2 for all partners forever", "Automatic root user MFA for all customers"],
        "a": [0, 1], "multi": True,
        "exp": "APN partners get training, events, and commercial benefits like volume discounts. EC2 is not free unlimited for partners. MFA is a security practice, not an APN automatic benefit.",
    },

    # ── GAP-FILL: Complete exam coverage (46 additional questions) ──

    # 1.2 — pillars not yet tested as correct answer
    {"d": 0, "t": "1.2", "q": "A team uses runbooks, monitors deployments, and improves processes after every outage. Which Well-Architected pillar are they focusing on?", "opts": ["Operational Excellence", "Cost Optimization", "Sustainability", "Performance Efficiency"], "a": 0, "exp": "Operational Excellence is about running and improving systems day to day — runbooks, monitoring, learning from incidents. Cost Optimization saves money. Sustainability is environmental. Performance Efficiency is speed and right-sizing."},
    {"d": 0, "t": "1.2", "q": "An app uses GPU instances only for video encoding and smaller instances for the website. Which pillar guides picking the right tool for each job?", "opts": ["Performance Efficiency", "Reliability", "Security", "Sustainability"], "a": 0, "exp": "Performance Efficiency means using the right resources for the workload — GPUs for heavy compute, smaller instances for light web traffic. Reliability is uptime. Security is protection. Sustainability is green efficiency."},

    # 1.3 — remaining 6 R's and migration tools
    {"d": 0, "t": "1.3", "q": "A startup rewrites their monolith into microservices built for AWS Lambda and DynamoDB. Which migration strategy is this?", "opts": ["Refactor (re-architect)", "Rehost (lift-and-shift)", "Retain", "Repurchase"], "a": 0, "exp": "Refactor means redesigning the app to be cloud-native. Rehost moves as-is. Retain keeps workloads on-premises. Repurchase replaces with SaaS like Salesforce."},
    {"d": 0, "t": "1.3", "q": "A company replaces its on-premises CRM with Salesforce.com instead of moving it to EC2. Which migration strategy is this?", "opts": ["Repurchase", "Rehost", "Refactor", "Replatform"], "a": 0, "exp": "Repurchase means moving to a different product, usually SaaS. Rehost lifts unchanged. Refactor rewrites. Replatform makes small optimizations."},
    {"d": 0, "t": "1.3", "q": "A bank decides to keep its mainframe on-premises for now while moving other apps to AWS. Which strategy is this?", "opts": ["Retain", "Retire", "Rehost", "Refactor"], "a": 0, "exp": "Retain means keeping some workloads on-premises. Retire shuts down unused apps. Rehost and Refactor move to cloud."},
    {"d": 0, "t": "1.3", "q": "A project manager wants one dashboard to track progress of multiple migration projects across the company. Which service helps?", "opts": ["AWS Migration Hub", "Amazon Macie", "AWS Budgets", "Amazon Lex"], "a": 0, "exp": "Migration Hub tracks migration progress across tools. Macie finds PII. Budgets alerts on spend. Lex builds chatbots."},
    {"d": 0, "t": "1.3", "q": "A team needs to sync 50 TB from an on-premises NAS to AWS S3 weekly over the network with automation. Which service fits?", "opts": ["AWS DataSync", "AWS Snowball (one-time ship)", "Amazon CloudFront", "AWS Direct Connect only"], "a": 0, "exp": "DataSync automates online data transfer between on-premises and AWS. Snowball is for huge one-time offline moves. CloudFront is CDN. Direct Connect is the pipe but DataSync does the sync."},
    {"d": 0, "t": "1.3", "q": "Leadership wants better environmental and social governance (ESG) outcomes from cloud adoption. Which framework addresses this alongside reduced business risk?", "opts": ["AWS Cloud Adoption Framework (CAF)", "AWS WAF", "Amazon EBS", "AWS Spot Fleet"], "a": 0, "exp": "CAF outcomes include improved ESG, reduced risk, and operational efficiency. WAF is a web firewall. EBS is storage. Spot Fleet runs interruptible EC2."},

    # 2.2 — Macie, Inspector, CloudWatch monitoring
    {"d": 1, "t": "2.2", "q": "A compliance officer needs to find credit card numbers accidentally stored in S3 buckets. Which service is built for this?", "opts": ["Amazon Macie", "AWS WAF", "Amazon GuardDuty", "AWS Shield"], "a": 0, "exp": "Macie uses ML to find sensitive data like PII in S3. WAF blocks web attacks. GuardDuty detects account threats. Shield stops DDoS."},
    {"d": 1, "t": "2.2", "q": "Before a release, a team scans EC2 instances for missing security patches and CVE vulnerabilities. Which service should they use?", "opts": ["Amazon Inspector", "Amazon Macie", "AWS Artifact", "AWS Budgets"], "a": 0, "exp": "Inspector scans EC2 and containers for CVEs and exposure. Macie finds PII in S3. Artifact has compliance PDFs. Budgets tracks spend."},
    {"d": 1, "t": "2.2", "q": "An ops team sets a CPU alarm that sends email when an EC2 instance exceeds 80% for five minutes. Which service collects metrics and triggers alarms?", "opts": ["Amazon CloudWatch", "AWS CloudTrail", "AWS Config", "AWS Artifact"], "a": 0, "exp": "CloudWatch monitors metrics, logs, and alarms. CloudTrail logs API calls. Config tracks resource configurations. Artifact hosts compliance reports."},

    # 2.3 — root user, federated, cross-account, policies
    {"d": 1, "t": "2.3", "q": "Select TWO actions that ONLY the AWS root user can perform (best practice: do these once, then use IAM daily).", "opts": ["Change the AWS account root email address", "Close/delete the AWS account", "Launch EC2 instances", "Read S3 objects with a bucket policy"], "a": [0, 1], "multi": True, "exp": "Only root can change root email and close the account. EC2 and S3 access should use IAM users/roles with least privilege — not root."},
    {"d": 1, "t": "2.3", "q": "Employees already have corporate Active Directory accounts. They want one login to access AWS without separate IAM passwords. What is this called?", "opts": ["Federated identity / SSO with IAM Identity Center", "Public S3 bucket access", "Root user sharing", "Spot Instance pricing"], "a": 0, "exp": "Federated identity connects your corporate directory to AWS via SSO (IAM Identity Center). Public S3 is insecure. Root sharing is dangerous. Spot is pricing."},
    {"d": 1, "t": "2.3", "q": "Account A needs to access resources in Account B without creating long-term keys. Which IAM feature enables this securely?", "opts": ["Cross-account IAM role", "Root user access keys in Account A", "Public security group", "Disable CloudTrail"], "a": 0, "exp": "Cross-account roles let one account assume temporary access in another. Root keys are never recommended. Public SGs are insecure. CloudTrail helps auditing."},
    {"d": 1, "t": "2.3", "q": "A security audit needs a report listing all IAM users and the age of their access keys. Which IAM feature provides this?", "opts": ["IAM credential report", "AWS Cost Explorer", "Amazon CloudFront", "AWS Snowball"], "a": 0, "exp": "The IAM credential report shows users, keys, and password status. Cost Explorer is billing. CloudFront is CDN. Snowball transfers data."},
    {"d": 1, "t": "2.3", "q": "A team needs AWS-maintained permission templates (e.g., ReadOnlyAccess) instead of writing JSON from scratch. Which policy type is this?", "opts": ["AWS managed policy", "Inline policy only", "S3 bucket policy only", "Security group rule"], "a": 0, "exp": "AWS managed policies are pre-built by AWS. Custom/inline policies are written by you. S3 bucket policies control bucket access. Security groups control network traffic."},

    # 2.4 — Trusted Advisor security
    {"d": 1, "t": "2.4", "q": "A company on Business Support sees Trusted Advisor flag an S3 bucket open to the world. Which service produced this security recommendation?", "opts": ["AWS Trusted Advisor", "AWS Artifact", "Amazon Redshift", "AWS Snowball"], "a": 0, "exp": "Trusted Advisor scans for security, cost, performance, fault tolerance, and limits. Artifact has compliance docs. Redshift is analytics. Snowball is migration."},

    # 3.3 — EC2 instance families and Dedicated Instances/Capacity
    {"d": 2, "t": "3.3", "q": "A science team runs heavy CPU calculations and batch processing. Which EC2 instance family is optimized for this?", "opts": ["Compute optimized (e.g., C-family instances)", "Storage optimized", "Memory optimized", "General purpose only always"], "a": 0, "exp": "Compute-optimized instances have high CPU for calculations. Storage-optimized is for large local disks (Hadoop). Memory-optimized is for big RAM. General purpose is balanced."},
    {"d": 2, "t": "3.3", "q": "A Hadoop cluster needs thousands of low-latency reads from local disks. Which EC2 instance type category fits best?", "opts": ["Storage optimized", "Compute optimized", "Memory optimized", "T2 burstable only"], "a": 0, "exp": "Storage-optimized instances have high disk throughput for data-heavy workloads. Compute-optimized is CPU-heavy. Memory-optimized is RAM-heavy. T2 is general burstable."},
    {"d": 2, "t": "3.3", "q": "An in-memory database needs the largest RAM possible on EC2. Which instance category should they choose?", "opts": ["Memory optimized", "Storage optimized", "Compute optimized", "Spot only"], "a": 0, "exp": "Memory-optimized instances (R-family) have high RAM for databases and caches. Storage-optimized is for disk I/O. Compute-optimized is CPU. Spot is a pricing model, not a category."},
    {"d": 2, "t": "3.3", "q": "A company needs physical isolation for compliance but does NOT need visibility into the physical host socket. Which option fits?", "opts": ["Dedicated Instances", "Dedicated Hosts with socket visibility", "Spot Instances", "Lambda"], "a": 0, "exp": "Dedicated Instances run on hardware dedicated to you without host-level control. Dedicated Hosts give physical server visibility for BYOL. Spot is interruptible spare capacity. Lambda is serverless."},
    {"d": 2, "t": "3.3", "q": "A team reserved EC2 capacity in a specific Availability Zone for a critical always-on app. Which purchasing option is this?", "opts": ["Capacity Reservations", "Spot Instances", "S3 Glacier", "AWS Budgets"], "a": 0, "exp": "Capacity Reservations guarantee capacity in an AZ. Spot is interruptible discount capacity. Glacier is archive storage. Budgets is cost alerts."},
    {"d": 2, "t": "3.3", "q": "A developer wants Docker containers on AWS without learning Kubernetes. Which service should they choose?", "opts": ["Amazon ECS", "Amazon EKS", "Amazon Redshift", "Amazon Route 53"], "a": 0, "exp": "ECS is AWS-native container orchestration without Kubernetes. EKS requires Kubernetes knowledge. Redshift is analytics. Route 53 is DNS."},

    # 3.4 — EC2-hosted vs managed DB
    {"d": 2, "t": "3.4", "q": "A team wants full control of MySQL including the OS and database tuning, accepting more management work. Which approach fits?", "opts": ["Install MySQL on EC2 (self-managed)", "Amazon RDS (AWS manages patching/backups)", "Amazon DynamoDB", "Amazon S3"], "a": 0, "exp": "MySQL on EC2 gives full control but you manage everything. RDS is managed — AWS handles backups and patching. DynamoDB is NoSQL. S3 is object storage."},

    # 3.5 — Security group stateful
    {"d": 2, "t": "3.5", "q": "A developer allows inbound HTTP on port 80 in a security group. Return traffic from the server to the client is automatically allowed. Why?", "opts": ["Security groups are stateful — return traffic is tracked automatically", "Security groups are stateless like NACLs", "NACLs always allow all outbound", "Route 53 handles return traffic"], "a": 0, "exp": "Security groups are stateful — if you allow inbound, the response goes back automatically. NACLs are stateless and need rules both ways. Route 53 is DNS."},

    # 3.6 — EBS, instance store, S3 classes
    {"d": 2, "t": "3.6", "q": "A database on EC2 needs a persistent disk that survives reboots and stays attached to that one instance. Which storage fits?", "opts": ["Amazon EBS", "EC2 instance store (ephemeral)", "Amazon S3", "Amazon CloudFront"], "a": 0, "exp": "EBS is persistent block storage for one EC2 instance. Instance store is temporary — data is lost if the instance stops/terminates. S3 is object storage. CloudFront is CDN."},
    {"d": 2, "t": "3.6", "q": "A gaming server needs the fastest temporary scratch disk but can lose data when the instance stops. Which storage should they use?", "opts": ["EC2 instance store (ephemeral)", "Amazon EBS", "Amazon EFS", "S3 Glacier Deep Archive"], "a": 0, "exp": "Instance store is physically attached fast storage but ephemeral (temporary). EBS persists. EFS is shared files. Glacier is cold archive."},
    {"d": 2, "t": "3.6", "q": "Backup files are accessed about once a month. S3 should automatically move older files to a cheaper tier. Which feature does this?", "opts": ["S3 lifecycle policy", "AWS Backup only", "EBS snapshot only", "Direct Connect"], "a": 0, "exp": "S3 lifecycle policies auto-transition objects to cheaper classes (IA, Glacier). AWS Backup centralizes backups across services. EBS snapshots backup volumes. Direct Connect is networking."},
    {"d": 2, "t": "3.6", "q": "A dataset is accessed unpredictably but S3 should automatically move objects between access tiers to save money. Which S3 feature helps?", "opts": ["S3 Intelligent-Tiering", "S3 Glacier Deep Archive only", "EBS Multi-Attach", "EFS One Zone-IA only"], "a": 0, "exp": "Intelligent-Tiering auto-moves objects between tiers based on access patterns. Glacier Deep Archive is for coldest archive. EBS Multi-Attach shares block storage. EFS One Zone is file storage."},

    # 3.7 — Rekognition, Comprehend, Textract
    {"d": 2, "t": "3.7", "q": "A social app needs to detect faces and inappropriate images in user uploads automatically. Which AI service fits?", "opts": ["Amazon Rekognition", "Amazon Athena", "AWS Glue", "Amazon Kendra"], "a": 0, "exp": "Rekognition analyzes images and video for faces, objects, and content moderation. Athena queries S3. Glue is ETL. Kendra is enterprise search."},
    {"d": 2, "t": "3.7", "q": "A marketing team wants to know if customer reviews are positive or negative without reading each one. Which service uses NLP for this?", "opts": ["Amazon Comprehend", "Amazon Lex", "Amazon Connect", "AWS IoT Core"], "a": 0, "exp": "Comprehend does NLP — sentiment analysis, entity extraction. Lex is chatbots. Connect is call center. IoT Core manages devices."},
    {"d": 2, "t": "3.7", "q": "A finance team scans thousands of scanned PDF invoices to extract text and numbers without manual typing. Which service fits?", "opts": ["Amazon Textract", "Amazon Macie", "Amazon GuardDuty", "AWS Shield"], "a": 0, "exp": "Textract extracts text and data from documents and forms. Macie finds PII in S3. GuardDuty detects threats. Shield stops DDoS."},

    # 3.8 — WorkSpaces Secure Browser, Solutions Architects, SNS
    {"d": 2, "t": "3.8", "q": "Contractors need to browse internal web apps securely from any device without installing a full desktop. Which service streams a secure browser?", "opts": ["Amazon WorkSpaces Secure Browser", "Amazon WorkSpaces full desktop", "AWS Snowball", "Amazon Redshift"], "a": 0, "exp": "WorkSpaces Secure Browser streams an isolated browser for secure web access. Full WorkSpaces is a complete virtual desktop. Snowball is data transfer. Redshift is analytics."},
    {"d": 2, "t": "3.8", "q": "A startup wants free architecture guidance from AWS before paying for a full migration project. Who typically provides this initial help?", "opts": ["AWS Solutions Architects", "AWS Trust and Safety team", "AWS Cost and Usage Report", "Amazon Glacier"], "a": 0, "exp": "Solutions Architects provide architecture guidance (often at no charge for planning). Trust and Safety handles abuse. CUR is billing data. Glacier is storage."},
    {"d": 2, "t": "3.8", "q": "One event must trigger email, SMS, and a Lambda function at the same time. Which service fans out to multiple subscribers?", "opts": ["Amazon SNS", "Amazon SQS queue only", "Amazon EBS", "AWS Direct Connect"], "a": 0, "exp": "SNS pub/sub sends one message to many subscribers (email, SMS, Lambda, SQS). SQS is a queue for one consumer pattern. EBS is storage. Direct Connect is networking."},

    # 4.1 — Savings Plans, RI in Organizations, inbound transfer
    {"d": 3, "t": "4.1", "q": "A company commits to $10/hour of compute usage for 3 years and wants the discount to apply across EC2, Lambda, and Fargate automatically. Which option fits?", "opts": ["Compute Savings Plans", "Dedicated Hosts only", "On-Demand only", "S3 Glacier"], "a": 0, "exp": "Compute Savings Plans apply flexibly across EC2, Lambda, and Fargate. Dedicated Hosts are physical isolation. On-Demand has no discount. Glacier is storage."},
    {"d": 3, "t": "4.1", "q": "Reserved Instance discounts from member accounts in AWS Organizations can apply to which billing arrangement?", "opts": ["Consolidated billing in the management account", "Each account billed completely separately with no org", "Only S3 storage charges", "IAM user passwords"], "a": 0, "exp": "With Organizations consolidated billing, RI benefits can share across accounts in the org. Separate billing doesn't share RIs. S3 and IAM are unrelated."},
    {"d": 3, "t": "4.1", "q": "A team uploads 500 GB of data from the internet into S3 in us-east-1. Which data transfer cost applies for inbound?", "opts": ["Inbound internet transfer is typically free; you pay for storage and outbound", "Inbound always costs more than outbound", "All transfer is free forever", "Only outbound is free"], "a": 0, "exp": "AWS typically does not charge for inbound data transfer from the internet. You pay for storage and for outbound/cross-Region transfer. Outbound is not free."},

    # 4.2 — SCPs, Trusted Advisor cost
    {"d": 3, "t": "4.2", "q": "A parent company must prevent developer accounts from launching resources outside us-east-1, even for admins. Which feature enforces this?", "opts": ["Service Control Policies (SCPs) in AWS Organizations", "IAM password policy only", "Security group inbound rule", "AWS Budgets alert"], "a": 0, "exp": "SCPs set maximum permissions for entire accounts — even admins can't bypass a deny. Password policy is for IAM passwords. Security groups control network. Budgets alerts on spend."},
    {"d": 3, "t": "4.2", "q": "Trusted Advisor flags idle EC2 instances and underused EBS volumes to save money. Which category is this?", "opts": ["Cost Optimization", "Security only", "Fault tolerance only", "IAM Identity Center"], "a": 0, "exp": "Idle resources and underused volumes are Cost Optimization recommendations. Trusted Advisor also has Security, Performance, Fault Tolerance, and Service Limits categories."},

    # 4.3 — Solutions Architects vs Pro Services, Prescriptive Guidance, whitepapers
    {"d": 3, "t": "4.3", "q": "Where can you find official AWS architecture whitepapers and best-practice guides for free?", "opts": ["AWS documentation and AWS Prescriptive Guidance on aws.amazon.com", "Only paid Professional Services contracts", "Amazon S3 Glacier archives only", "Third-party Reddit posts only"], "a": 0, "exp": "AWS publishes free whitepapers, docs, and Prescriptive Guidance on official sites. Professional Services is paid consulting. Glacier is storage. Reddit is not official."},
    {"d": 3, "t": "4.3", "q": "Select TWO ways AWS helps customers optimize cost and monitor environment health.", "opts": ["AWS Trusted Advisor recommendations", "AWS Health Dashboard personalized alerts", "Disabling all CloudWatch alarms", "Removing MFA from root"], "a": [0, 1], "multi": True, "exp": "Trusted Advisor suggests cost/security improvements. Health Dashboard alerts about events affecting your resources. Disabling alarms and removing MFA are bad practices."},
]
