"""Additional CLF-C02 practice questions for the study app."""

EXTRA_QUESTIONS = [
    # ── 1.1 Benefits of AWS Cloud (3) ──
    {
        "d": 0, "t": "1.1",
        "q": "A bakery chain opens pop-up shops in five cities for one weekend. They need servers only during the event and want to shut them down Monday morning. Which cloud benefit fits this pay-only-when-used model?",
        "opts": ["Variable operational expense instead of buying servers upfront", "Dedicated physical hosts in each city", "Permanent reserved capacity for 3 years", "On-premises data center expansion"],
        "a": 0,
        "exp": "Pay-as-you-go OpEx lets you run servers for a short time and stop paying when done. Dedicated hosts and 3-year reservations are for steady long-term use. Building data centers is slow and costly.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "A mobile game studio in Tokyo wants players in Brazil to see low lag without building a data center in South America. Select TWO AWS features that help reach users globally.",
        "opts": ["Deploy in Regions close to players", "Use edge locations to cache content near users", "Run everything in one Availability Zone only", "Keep all servers on-premises in Tokyo"],
        "a": [0, 1], "multi": True,
        "exp": "Regions place apps near users geographically. Edge locations (CloudFront) cache files close to players for speed. One AZ is not global and lacks backup. On-premises in Tokyo alone cannot serve Brazil well.",
    },
    {
        "d": 0, "t": "1.1",
        "q": "A founder says agility is why they chose AWS: they can test three product ideas in parallel this month and cancel two that fail. What makes this possible?",
        "opts": ["Quickly launch and tear down resources without buying hardware", "Snowball devices for every test", "Mandatory 5-year contracts on all services", "Building a private data center first"],
        "a": 0,
        "exp": "Cloud agility means fast experiments without hardware purchases. Snowball moves data, not product testing. AWS rarely forces long contracts for basic services. Private data centers take months or years.",
    },
    # ── 1.2 Well-Architected Framework (2) ──
    {
        "d": 0, "t": "1.2",
        "q": "An ops team writes runbooks, automates deployments, and reviews incidents after outages. Which Well-Architected pillar are they improving?",
        "opts": ["Operational Excellence", "Cost Optimization", "Performance Efficiency", "Sustainability"],
        "a": 0,
        "exp": "Operational Excellence is about running systems well with procedures and learning from events. Cost Optimization saves money. Performance Efficiency picks the right speed tools. Sustainability is environmental impact.",
    },
    {
        "d": 0, "t": "1.2",
        "q": "A company schedules non-urgent batch jobs at night when electricity is greener and uses smaller instances when load is low. Select TWO pillars this design supports.",
        "opts": ["Sustainability", "Cost Optimization", "Security only", "Reliability only"],
        "a": [0, 1], "multi": True,
        "exp": "Running efficient workloads and right-sizing saves money (Cost Optimization) and uses less energy (Sustainability). Security and Reliability are important but not the main focus of green scheduling and smaller instances.",
    },
    # ── 1.3 Migration & Cloud Adoption (3) ──
    {
        "d": 0, "t": "1.3",
        "q": "A team moves their Windows VM to EC2 with almost no code changes, only updating the database connection string. Which migration strategy is this?",
        "opts": ["Rehost (lift-and-shift)", "Refactor", "Repurchase", "Retire"],
        "a": 0,
        "exp": "Rehost moves the app as-is to the cloud with minimal changes. Refactor rewrites for cloud-native design. Repurchase switches to SaaS. Retire shuts down unused apps.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "An oil company has 80 TB of seismic data on tape in a remote site with only a slow satellite link. They need a one-time bulk move to S3. What should they use?",
        "opts": ["AWS Snowball Edge device shipped to the site", "AWS DataSync over the satellite link only", "Amazon CloudFront distribution", "AWS Direct Connect without any transfer tool"],
        "a": 0,
        "exp": "Snowball ships a rugged device for huge offline transfers when the network is too slow. DataSync needs a workable network for ongoing sync. CloudFront caches web content. Direct Connect is a private pipe, not a bulk copy tool.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "Before migration, leadership wants to align people skills, governance rules, and platform design using AWS guidance. Which framework provides these six perspectives?",
        "opts": ["AWS Cloud Adoption Framework (CAF)", "Amazon GuardDuty", "AWS WAF", "Amazon EBS"],
        "a": 0,
        "exp": "CAF covers Business, People, Governance, Platform, Security, and Operations for adoption planning. GuardDuty finds threats. WAF blocks web attacks. EBS is block storage.",
    },
    {
        "d": 0, "t": "1.3",
        "q": "A company shuts down an unused legacy reporting server and moves a second app to SaaS instead of EC2. Select TWO migration strategies being used.",
        "opts": ["Retire (decommission unused workloads)", "Repurchase (move to SaaS product)", "Rehost unchanged to EC2", "Refactor to microservices"],
        "a": [0, 1], "multi": True,
        "exp": "Retire removes workloads you no longer need. Repurchase replaces software with SaaS like Salesforce. Rehost moves as-is to cloud. Refactor rewrites the architecture.",
    },
    # ── 1.4 Cloud Economics (2) ──
    {
        "d": 0, "t": "1.4",
        "q": "A CFO compares buying servers that sit idle 70% of the time versus paying AWS only when servers run. Which economic idea explains the cloud savings?",
        "opts": ["Higher utilization through shared infrastructure and pay-per-use", "Each customer gets their own private factory", "Cloud always costs more than owned hardware", "CapEx is always cheaper than OpEx"],
        "a": 0,
        "exp": "Shared cloud infrastructure improves utilization so you do not pay for idle hardware. Private factories per customer would be expensive. Cloud is often cheaper for variable workloads. CapEx is not always cheaper.",
    },
    {
        "d": 0, "t": "1.4",
        "q": "A DBA team uses scripts to resize databases nightly based on usage instead of hiring staff to click buttons. Which cost-saving approach is this?",
        "opts": ["Automation reducing manual labor", "Buying the largest instance always", "Disabling all monitoring", "Adding more Regions for every app"],
        "a": 0,
        "exp": "Automation replaces repetitive manual work and saves labor cost. Always using the biggest instance wastes money. Turning off monitoring risks outages. Extra Regions add cost and complexity.",
    },
    {
        "d": 0, "t": "1.4",
        "q": "A facilities manager lists costs they will no longer pay after moving apps to AWS. Select TWO expenses cloud customers typically avoid compared to owning a data center.",
        "opts": ["Building and maintaining their own server rooms", "Paying for electricity and cooling in a company data center", "Paying for AWS service usage they actually consume", "Buying network cables for AWS Regions"],
        "a": [0, 1], "multi": True,
        "exp": "On-premises means you fund buildings, power, and cooling yourself. In cloud you pay for services used instead. AWS owns Region facilities — you do not buy their cables.",
    },
    # ── 2.1 Shared Responsibility Model (3) ──
    {
        "d": 1, "t": "2.1",
        "q": "After a security review, auditors ask who must encrypt sensitive files stored in the customer's S3 buckets. Under the shared responsibility model, who owns this task?",
        "opts": ["The customer configures encryption and access", "AWS automatically encrypts all customer data with no setup", "GuardDuty encrypts buckets", "CloudFront encrypts S3 objects by default"],
        "a": 0,
        "exp": "Customers secure data IN the cloud, including choosing encryption and bucket policies. AWS provides encryption options but you must configure them. GuardDuty detects threats. CloudFront is a CDN.",
    },
    {
        "d": 1, "t": "2.1",
        "q": "Select TWO items that are AWS's responsibility under the shared responsibility model for EC2.",
        "opts": ["Physical security of data centers", "Patching the guest operating system on your instance", "Hypervisor and underlying hardware maintenance", "Configuring your application's user passwords"],
        "a": [0, 2], "multi": True,
        "exp": "AWS secures the cloud platform: buildings, hardware, and hypervisor. You patch the OS on EC2 and manage app passwords. Those are customer responsibilities IN the cloud.",
    },
    {
        "d": 1, "t": "2.1",
        "q": "A team uses Amazon RDS PostgreSQL. AWS applies database engine patches, but the team still controls table data and who can connect. Why does RDS shift some work to AWS?",
        "opts": ["RDS is a managed service so AWS handles more of the stack", "RDS means the customer owns all physical servers", "RDS removes the need for any access control", "RDS is the same responsibility level as raw EC2"],
        "a": 0,
        "exp": "Managed services like RDS mean AWS maintains more layers (engine patches, infrastructure). Customers still manage data and permissions. RDS does not remove access control. Raw EC2 leaves more to the customer.",
    },
    # ── 2.2 Security, Governance & Compliance (4) ──
    {
        "d": 1, "t": "2.2",
        "q": "A security analyst sees GuardDuty flag unusual API calls from a foreign IP, Inspector report open ports on EC2, and Macie alert on SSN patterns in S3. Select TWO services that produced threat and vulnerability findings (not PII discovery).",
        "opts": ["Amazon GuardDuty", "Amazon Inspector", "Amazon Macie", "AWS Artifact"],
        "a": [0, 1], "multi": True,
        "exp": "GuardDuty finds suspicious account activity. Inspector scans for vulnerabilities and exposure on workloads. Macie discovers sensitive data in S3. Artifact hosts compliance PDFs, not live threat alerts.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "A healthcare app stores patient records in S3. Compliance needs proof buckets stay encrypted and public access stays blocked over time. Which service continuously checks resource settings against rules?",
        "opts": ["AWS Config", "Amazon Macie only", "AWS Pricing Calculator", "Amazon CloudFront"],
        "a": 0,
        "exp": "Config tracks configuration history and evaluates rules like encryption enabled. Macie finds PII content inside objects. Pricing Calculator estimates costs. CloudFront delivers cached content.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "An auditor needs downloadable SOC reports to prove AWS meets compliance standards before signing a vendor contract. Where should they get these documents?",
        "opts": ["AWS Artifact", "Amazon GuardDuty", "AWS CloudTrail", "Amazon Inspector"],
        "a": 0,
        "exp": "Artifact provides on-demand compliance reports and agreements. GuardDuty detects threats. CloudTrail logs API activity. Inspector scans for vulnerabilities.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "A DLP team must find passport numbers accidentally uploaded to dozens of S3 buckets across the account. Which service is purpose-built for discovering sensitive data in S3?",
        "opts": ["Amazon Macie", "AWS WAF", "Amazon GuardDuty", "AWS Shield Standard"],
        "a": 0,
        "exp": "Macie uses machine learning to find PII and sensitive patterns in S3. WAF blocks web attacks at the application layer. GuardDuty watches for malicious activity. Shield protects against DDoS.",
    },
    {
        "d": 1, "t": "2.2",
        "q": "After a suspected breach, investigators need a record of every API call made in the account, including who deleted a security group. Select TWO services that help audit account activity and configuration.",
        "opts": ["AWS CloudTrail", "AWS Config", "Amazon Macie", "AWS Pricing Calculator"],
        "a": [0, 1], "multi": True,
        "exp": "CloudTrail logs API calls with identity and time. Config records how resources were configured over time. Macie finds sensitive data in S3. Pricing Calculator estimates costs.",
    },
    # ── 2.3 IAM & Access Management (3) ──
    {
        "d": 1, "t": "2.3",
        "q": "A Lambda function needs read access to a DynamoDB table. The developer should attach permissions to what instead of embedding access keys in code?",
        "opts": ["An IAM role assumed by the Lambda function", "The root user's access keys", "A public S3 bucket policy", "A security group rule"],
        "a": 0,
        "exp": "Roles give temporary credentials to AWS services safely. Root keys are dangerous and should never be in code. S3 policies and security groups do not grant Lambda AWS API access.",
    },
    {
        "d": 1, "t": "2.3",
        "q": "Select TWO best practices for the AWS account root user.",
        "opts": ["Enable MFA on the root account", "Create an admin IAM user for daily work instead of using root", "Share root password with the whole team", "Create access keys for root and put them in GitHub"],
        "a": [0, 1], "multi": True,
        "exp": "Protect root with MFA and use IAM users or SSO for everyday tasks. Sharing root or putting root keys in code creates huge security risk.",
    },
    {
        "d": 1, "t": "2.3",
        "q": "A rotating database password must be fetched by an app without hard-coding it in source code. Which service stores and auto-rotates secrets?",
        "opts": ["AWS Secrets Manager", "Amazon S3 public bucket", "AWS Cost Explorer", "Amazon Route 53"],
        "a": 0,
        "exp": "Secrets Manager stores passwords and can rotate them automatically. Public S3 is insecure. Cost Explorer shows billing. Route 53 is DNS.",
    },
    # ── 2.4 Security Components & Resources (3) ──
    {
        "d": 1, "t": "2.4",
        "q": "A public website behind Application Load Balancer faces SQL injection attempts in HTTP requests. Which service should block these web attack patterns?",
        "opts": ["AWS WAF", "Amazon GuardDuty", "Amazon Macie", "AWS Cost Explorer"],
        "a": 0,
        "exp": "WAF inspects HTTP/HTTPS requests and blocks attacks like SQL injection. GuardDuty finds account-level threats. Macie scans S3 for sensitive data. Cost Explorer analyzes spending.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "During a holiday sale, a shop's site is hit with a massive flood of junk traffic trying to crash it. Select TWO services that help protect against this kind of attack.",
        "opts": ["AWS Shield (DDoS protection)", "AWS WAF (can block bad request patterns)", "Amazon Macie", "AWS Pricing Calculator"],
        "a": [0, 1], "multi": True,
        "exp": "Shield mitigates DDoS floods at the network edge. WAF can block malicious HTTP patterns during an attack. Macie finds PII in storage. Pricing Calculator estimates future bills.",
    },
    {
        "d": 1, "t": "2.4",
        "q": "A security team wants free basic checks that flag open security groups and MFA not enabled on the root account. Which tool provides these recommendations on Business Support?",
        "opts": ["AWS Trusted Advisor", "AWS Artifact only", "Amazon Inspector only", "AWS Snowball"],
        "a": 0,
        "exp": "Trusted Advisor scans for security, cost, performance, fault tolerance, and limits. Artifact has compliance docs. Inspector scans workloads for CVEs. Snowball transfers data.",
    },
    # ── 3.1 Deploy & Operate in AWS (2) ──
    {
        "d": 2, "t": "3.1",
        "q": "A DevOps engineer wants the same VPC, subnets, and EC2 setup in dev, test, and prod every time with one command. Which approach ensures repeatable infrastructure?",
        "opts": ["AWS CloudFormation templates", "Clicking the console differently each time", "Emailing screenshots of settings", "Using only Snowball"],
        "a": 0,
        "exp": "CloudFormation is Infrastructure as Code for identical repeatable deployments. Manual console clicks drift over time. Screenshots are not automation. Snowball moves data.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "A company keeps payroll on-premises but runs its public website on AWS. Which cloud deployment model describes this mix?",
        "opts": ["Hybrid cloud", "Public cloud only", "Private cloud only on AWS", "Community cloud"],
        "a": 0,
        "exp": "Hybrid combines on-premises and cloud. Public-only means everything on shared AWS infrastructure. Private cloud on AWS could mean isolated VPC but payroll is still on-prem here. Community cloud is shared by related orgs.",
    },
    {
        "d": 2, "t": "3.1",
        "q": "An engineer needs to create an S3 bucket from a laptop script and later from a Python app. Select TWO valid ways to interact with AWS for this task.",
        "opts": ["AWS CLI", "AWS SDK in application code", "Only the root user console with no API", "AWS Snowball device only"],
        "a": [0, 1], "multi": True,
        "exp": "CLI and SDKs both call AWS APIs for automation. Root console-only is bad practice and not required. Snowball transfers bulk data, not routine bucket creation.",
    },
    # ── 3.2 Global Infrastructure (2) ──
    {
        "d": 2, "t": "3.2",
        "q": "A bank in Germany must keep customer data inside the EU for legal reasons. Which infrastructure choice helps meet data residency rules?",
        "opts": ["Deploy in an EU AWS Region such as eu-central-1", "Use only US Regions for lower cost", "Store data only on CloudFront edge caches", "Use a single subnet with no Region choice"],
        "a": 0,
        "exp": "Choosing an EU Region keeps primary data storage in the EU. US Regions may violate residency rules. Edge caches are for delivery, not primary regulated storage. Subnets exist inside a Region you must pick correctly.",
    },
    {
        "d": 2, "t": "3.2",
        "q": "A payment API runs in three Availability Zones in one Region so one data center fire does not take the service offline. Which concept does this design follow?",
        "opts": ["High availability across multiple AZs", "Single point of failure on purpose", "Multi-Region disaster recovery only", "Edge location primary storage"],
        "a": 0,
        "exp": "Multiple AZs in one Region provide high availability within that Region. One AZ on purpose is fragile. Multi-Region DR uses another Region entirely. Edge locations cache content; they are not primary databases.",
    },
    {
        "d": 2, "t": "3.2",
        "q": "A global bank wants fast failover if an entire Region fails and also low latency in each country. Select TWO infrastructure strategies that address these goals.",
        "opts": ["Multi-Region deployment for disaster recovery", "Use Regions geographically close to customers", "Run production in a single Availability Zone", "Store primary databases only on Snowball"],
        "a": [0, 1], "multi": True,
        "exp": "Multi-Region protects against Regional outages. Nearby Regions reduce latency for local users. One AZ is fragile. Snowball is offline data transfer, not production hosting.",
    },
    # ── 3.3 Compute Services (4) ──
    {
        "d": 2, "t": "3.3",
        "q": "A startup runs 200 short-lived container tasks per hour and never wants to patch EC2 servers. Which compute option fits best?",
        "opts": ["AWS Fargate with ECS or EKS", "Self-managed EC2 with manual Docker only", "Amazon Redshift clusters", "Dedicated Hosts for every task"],
        "a": 0,
        "exp": "Fargate runs containers without managing servers. Manual EC2 Docker means you patch and scale servers yourself. Redshift is analytics. Dedicated Hosts are for isolation, not serverless containers.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "Select TWO differences between Amazon ECS and Amazon EKS for a team planning container workloads.",
        "opts": ["EKS runs Kubernetes; ECS uses AWS-native orchestration", "ECS requires Kubernetes expertise; EKS does not", "Both can use Fargate to avoid managing EC2", "EKS is only for relational databases"],
        "a": [0, 2], "multi": True,
        "exp": "EKS is managed Kubernetes. ECS is AWS's own orchestrator without Kubernetes. Both support Fargate. EKS is not a database service — that is backwards.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "A photo app uploads spike every evening. The team wants EC2 instances added automatically when CPU is high and removed when quiet. Which services work together?",
        "opts": ["Amazon EC2 Auto Scaling with CloudWatch alarms", "Manual SSH and start/stop scripts only", "Amazon S3 lifecycle rules", "AWS Budgets alone"],
        "a": 0,
        "exp": "Auto Scaling changes instance count based on metrics like CPU from CloudWatch. Manual scripts do not scale fast enough. S3 lifecycle moves objects between storage classes. Budgets alert on spend, not CPU.",
    },
    {
        "d": 2, "t": "3.3",
        "q": "A batch job can stop and restart without harm and needs the lowest EC2 price. Which purchasing option should they choose?",
        "opts": ["Spot Instances", "On-Demand with no interruption risk", "Dedicated Hosts for compliance", "Reserved Instances for 3 years"],
        "a": 0,
        "exp": "Spot offers deep discounts on spare capacity for interruptible work. On-Demand costs more but is stable. Dedicated Hosts are for isolation. Reserved Instances need long steady commitment.",
    },
    # ── 3.4 Database Services (2) ──
    {
        "d": 2, "t": "3.4",
        "q": "A shopping cart app needs single-digit millisecond reads at millions of requests per second with no fixed schema. Which database fits?",
        "opts": ["Amazon DynamoDB", "Amazon RDS MySQL", "Amazon Redshift", "Amazon EBS volume"],
        "a": 0,
        "exp": "DynamoDB is serverless NoSQL built for massive scale and low latency. RDS is relational SQL. Redshift is a warehouse for analytics. EBS is block storage, not a database.",
    },
    {
        "d": 2, "t": "3.4",
        "q": "A team migrates Oracle on-premises to PostgreSQL on AWS and must convert stored procedures and schema automatically. Which tools help this database move?",
        "opts": ["AWS DMS plus AWS Schema Conversion Tool (SCT)", "Amazon Macie plus AWS WAF", "Amazon CloudFront plus Route 53", "AWS Snowball only without DMS"],
        "a": 0,
        "exp": "DMS replicates data during migration. SCT converts schemas between engines. Macie and WAF are security services. CloudFront and Route 53 are delivery and DNS. Snowball moves files, not live DB replication.",
    },
    {
        "d": 2, "t": "3.4",
        "q": "A SaaS product needs a managed SQL database with automatic backups and Multi-AZ failover without the team patching the database engine OS. Select TWO AWS services that fit relational workloads.",
        "opts": ["Amazon RDS", "Amazon Aurora", "Amazon DynamoDB", "Amazon S3"],
        "a": [0, 1], "multi": True,
        "exp": "RDS and Aurora are managed relational databases with backups and HA options. DynamoDB is NoSQL. S3 is object storage, not a SQL database.",
    },
    # ── 3.5 Network Services (4) ──
    {
        "d": 2, "t": "3.5",
        "q": "A subnet must block traffic from a known bad IP range at the subnet boundary, while instances use normal allow rules. Which firewall operates at the subnet level with explicit deny?",
        "opts": ["Network ACL (NACL)", "Security group on the instance", "AWS WAF on the load balancer", "Amazon Macie"],
        "a": 0,
        "exp": "NACLs are stateless subnet firewalls that support deny rules. Security groups only allow traffic at the instance level. WAF filters HTTP requests. Macie scans S3 content.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "Select TWO correct statements comparing security groups and network ACLs.",
        "opts": ["Security groups are stateful; NACLs are stateless", "NACLs apply at the subnet level; security groups apply to instances", "Security groups support explicit deny rules for every port", "NACLs are attached to a single EC2 instance only"],
        "a": [0, 1], "multi": True,
        "exp": "Security groups track connection state and attach to ENIs/instances. NACLs filter subnet traffic and need return rules because they are stateless. Security groups only allow (implicit deny). NACLs are not per-instance.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "Users type www.example.com in a browser and should reach the load balancer even if one server fails. Which service provides DNS routing and health checks?",
        "opts": ["Amazon Route 53", "Amazon VPC only", "AWS Direct Connect only", "Amazon GuardDuty"],
        "a": 0,
        "exp": "Route 53 is DNS with routing policies and health checks. VPC is your private network but not public DNS names. Direct Connect is a private link to AWS. GuardDuty detects threats.",
    },
    {
        "d": 2, "t": "3.5",
        "q": "A corporate office needs a private encrypted tunnel over the public internet to a VPC instead of sending traffic over the open internet unprotected. Which connection type fits?",
        "opts": ["Site-to-Site VPN", "Internet Gateway alone with no encryption", "Amazon S3 bucket policy", "AWS Budgets"],
        "a": 0,
        "exp": "Site-to-Site VPN creates an encrypted tunnel from on-premises to AWS. An Internet Gateway lets public subnets reach the internet but is not a private office tunnel. S3 policies and Budgets are unrelated.",
    },
    # ── 3.6 Storage Services (4) ──
    {
        "d": 2, "t": "3.6",
        "q": "A web app stores millions of user photos that must be reachable by URL and rarely change once uploaded. Which storage service fits?",
        "opts": ["Amazon S3", "Amazon EBS attached to one EC2", "Amazon EFS for shared POSIX files", "EC2 instance store only"],
        "a": 0,
        "exp": "S3 is object storage ideal for files served over HTTP. EBS is a disk for one instance. EFS is shared file storage for many servers. Instance store is temporary local disk.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "Ten Linux web servers must read and write the same log folder at the same time like a shared network drive. Which storage should they mount?",
        "opts": ["Amazon EFS", "Amazon EBS on one instance only", "S3 Glacier Deep Archive", "AWS Snowball"],
        "a": 0,
        "exp": "EFS provides shared NFS file storage across many EC2 instances. EBS normally attaches to one instance (Multi-Attach exists but EFS is the classic shared file answer). Glacier is cold archive. Snowball moves data offline.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "An architect picks storage for three workloads: user photos via HTTPS, a MySQL disk on one EC2, and shared config files across ten servers. Select TWO correct pairings.",
        "opts": ["User photos → Amazon S3", "MySQL disk on one EC2 → Amazon EBS", "Shared config across servers → Amazon EBS on one server only", "User photos → EC2 instance store only"],
        "a": [0, 1], "multi": True,
        "exp": "S3 serves objects over the web. EBS is a persistent disk for one instance like a database. EBS on one server cannot share files across ten hosts — use EFS for that. Instance store is temporary and not ideal for public photo hosting.",
    },
    {
        "d": 2, "t": "3.6",
        "q": "A Windows team needs a fully managed SMB file share in AWS that integrates with Active Directory. Which service should they evaluate?",
        "opts": ["Amazon FSx for Windows File Server", "Amazon S3 Standard only", "Amazon DynamoDB", "AWS WAF"],
        "a": 0,
        "exp": "FSx for Windows provides managed Windows file shares with AD integration. S3 is object storage. DynamoDB is NoSQL. WAF protects web apps.",
    },
    # ── 3.7 AI/ML & Analytics (2) ──
    {
        "d": 2, "t": "3.7",
        "q": "An analyst has CSV and JSON files in S3 and wants to run SQL queries without provisioning a database server. Which service queries S3 directly?",
        "opts": ["Amazon Athena", "Amazon RDS", "Amazon Redshift provisioned only", "Amazon EBS"],
        "a": 0,
        "exp": "Athena runs SQL on S3 data serverlessly. RDS and Redshift are database services you manage or provision. EBS is block storage.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "A ride-sharing app streams live GPS events from thousands of cars and must process them in real time. Which service handles high-volume streaming data?",
        "opts": ["Amazon Kinesis", "Amazon S3 Glacier", "AWS Snowball", "Amazon Route 53"],
        "a": 0,
        "exp": "Kinesis ingests and processes real-time data streams. Glacier is slow archive storage. Snowball is offline transfer. Route 53 is DNS.",
    },
    {
        "d": 2, "t": "3.7",
        "q": "A data team must clean raw sales files, load them into a warehouse, and build executive charts. Select TWO services commonly used for ETL and business dashboards.",
        "opts": ["AWS Glue", "Amazon QuickSight", "Amazon GuardDuty", "AWS WAF"],
        "a": [0, 1], "multi": True,
        "exp": "Glue prepares and transforms data (ETL). QuickSight builds BI dashboards and charts. GuardDuty detects threats. WAF blocks web attacks.",
    },
    # ── 3.8 Other AWS Services (2) ──
    {
        "d": 2, "t": "3.8",
        "q": "An order system must process payments one at a time in order so two workers never charge the same order twice. Which messaging pattern fits?",
        "opts": ["Amazon SQS queue", "Amazon SNS topic fan-out only", "Amazon CloudFront", "AWS Direct Connect"],
        "a": 0,
        "exp": "SQS queues let one consumer process messages in order reliably. SNS broadcasts to many subscribers at once. CloudFront caches content. Direct Connect is networking.",
    },
    {
        "d": 2, "t": "3.8",
        "q": "Select TWO services that help build and deliver a CI/CD pipeline on AWS.",
        "opts": ["AWS CodePipeline", "AWS CodeBuild", "Amazon Macie", "AWS Snowball Edge only"],
        "a": [0, 1], "multi": True,
        "exp": "CodePipeline orchestrates release stages. CodeBuild compiles and tests code. Macie finds sensitive data. Snowball Edge is for data transfer, not software pipelines.",
    },
    # ── 4.1 Pricing Models (2) ──
    {
        "d": 3, "t": "4.1",
        "q": "A company runs steady EC2 24/7 for three years and wants the largest discount with a commitment. Which pricing model should they consider first?",
        "opts": ["Reserved Instances or Savings Plans", "Spot Instances for all production traffic", "On-Demand with no commitment", "Pay only for data transfer inbound"],
        "a": 0,
        "exp": "Reserved Instances and Savings Plans give big discounts for long steady usage. Spot can be interrupted — bad for always-on production. On-Demand has no discount. Inbound transfer is often free but that is not an instance pricing model.",
    },
    {
        "d": 3, "t": "4.1",
        "q": "Legal archives must be kept 7 years, accessed almost never, and cost as little as possible per gigabyte. Which S3 storage class fits?",
        "opts": ["S3 Glacier Deep Archive", "S3 Standard for frequent access", "S3 Intelligent-Tiering for hot data", "EBS gp3 volumes"],
        "a": 0,
        "exp": "Glacier Deep Archive is the cheapest S3 class for rare access over years. Standard is for frequent use. Intelligent-Tiering optimizes active objects. EBS is block storage on EC2.",
    },
    {
        "d": 3, "t": "4.1",
        "q": "A video renderer uses Spot Instances for batch frames but keeps the customer-facing API on stable On-Demand instances. Select TWO pricing models used in this design.",
        "opts": ["Spot Instances for interruptible batch work", "On-Demand for steady production API", "Reserved Instances required for Spot", "S3 Glacier for running the API"],
        "a": [0, 1], "multi": True,
        "exp": "Spot saves money on fault-tolerant batch jobs. On-Demand keeps the API running without interruption. Spot does not require Reserved Instances. Glacier is storage, not compute for an API.",
    },
    # ── 4.2 Billing, Budget & Cost Management (4) ──
    {
        "d": 3, "t": "4.2",
        "q": "A project lead is designing a new three-tier app and wants to guess monthly cost before anything is deployed. Which tool should they use?",
        "opts": ["AWS Pricing Calculator", "AWS Cost Explorer", "AWS Budgets", "AWS CloudTrail"],
        "a": 0,
        "exp": "Pricing Calculator estimates future costs from a planned architecture. Cost Explorer analyzes past and forecasted actual bills. Budgets sends alerts when spend crosses limits. CloudTrail logs API calls.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "Finance wants an email when monthly AWS spend goes over $5,000 or forecasted spend will exceed it next week. Which service sends those alerts?",
        "opts": ["AWS Budgets", "AWS Pricing Calculator", "Amazon Inspector", "Amazon Macie"],
        "a": 0,
        "exp": "Budgets sets cost and usage thresholds with notifications. Pricing Calculator estimates before deployment. Inspector and Macie are security services.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "After deployment, a manager needs charts showing which services cost the most last quarter and a forecast for next month. Which tool provides this?",
        "opts": ["AWS Cost Explorer", "AWS Pricing Calculator", "AWS Artifact", "AWS WAF"],
        "a": 0,
        "exp": "Cost Explorer visualizes historical spend and forecasts by service. Pricing Calculator is pre-deployment estimates. Artifact has compliance reports. WAF protects web apps.",
    },
    {
        "d": 3, "t": "4.2",
        "q": "Select TWO actions that help show each department's share of the AWS bill on one consolidated invoice.",
        "opts": ["Apply cost allocation tags to resources", "Use AWS Organizations consolidated billing", "Disable all CloudWatch metrics", "Remove encryption from S3"],
        "a": [0, 1], "multi": True,
        "exp": "Tags let Cost Explorer split spend by team or project. Organizations consolidates many accounts onto one bill. Disabling metrics hurts operations. Removing encryption is insecure and unrelated to billing splits.",
    },
    # ── 4.3 Support & Resources (2) ──
    {
        "d": 3, "t": "4.3",
        "q": "Production is down at 3 AM on a Saturday and the team needs 24/7 phone support with a Technical Account Manager long term. Which support plan fits?",
        "opts": ["Enterprise Support", "Basic Support only", "Developer Support only", "No support plan — forums only"],
        "a": 0,
        "exp": "Enterprise Support includes 24/7 phone, fast response, and a dedicated TAM. Basic is free docs and forums. Developer has business-hours email only. Forums alone are not 24/7 phone support.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "A scheduled maintenance event will reboot RDS instances in your Region next Tuesday. Where should admins look for personalized alerts about impact to their resources?",
        "opts": ["AWS Health Dashboard", "AWS Pricing Calculator", "Amazon Macie", "AWS Snowball status page only"],
        "a": 0,
        "exp": "AWS Health Dashboard shows personalized events affecting your account like planned maintenance. Pricing Calculator estimates costs. Macie finds PII. Snowball is a transfer device.",
    },
    {
        "d": 3, "t": "4.3",
        "q": "A developer is stuck on an error message at night on Basic Support. Select TWO free AWS resources they can use before upgrading support plans.",
        "opts": ["AWS Documentation", "AWS re:Post community forums", "24/7 Enterprise phone hotline", "Dedicated Technical Account Manager"],
        "a": [0, 1], "multi": True,
        "exp": "Docs and re:Post are free self-help on Basic Support. Enterprise phone and a TAM require paid Enterprise (or similar) support plans.",
    },
]
