"""Flashcards for CLF-C02 — service comparisons, traps, and key terms."""

FLASHCARDS = [
    # Domain 1 — Cloud Concepts
    {"d": 0, "term": "CapEx vs OpEx", "def": "CapEx = you buy servers upfront like buying a car. OpEx = you pay AWS monthly like a Netflix subscription. Cloud turns CapEx into OpEx."},
    {"d": 0, "term": "Elasticity", "def": "Servers grow when traffic spikes and shrink when quiet — like hiring extra cashiers only on Black Friday."},
    {"d": 0, "term": "Agility", "def": "Try new ideas fast without buying hardware — like testing a food truck before opening a restaurant."},
    {"d": 0, "term": "High availability (HA)", "def": "App stays online when something breaks — use multiple Availability Zones and load balancers."},
    {"d": 0, "term": "Fault tolerance", "def": "One broken part does not kill the whole system — backups pick up the work."},
    {"d": 0, "term": "Economies of scale", "def": "AWS buys millions of servers cheaply and passes savings to you — warehouse club pricing."},
    {"d": 0, "term": "Region vs AZ vs Edge", "def": "Region = country-sized area. AZ = separate building inside Region. Edge = tiny cache shop near users (CloudFront)."},
    {"d": 0, "term": "Public vs Private vs Hybrid", "def": "Public = AWS shared cloud. Private = your own servers. Hybrid = mix of both — very common."},
    {"d": 0, "term": "Well-Architected — 6 pillars", "def": "Operations, Security, Reliability, Performance, Cost, Sustainability — rules for building on AWS."},
    {"d": 0, "term": "TRAP: Pay for unused servers", "def": "NOT a cloud benefit! Cloud lets you STOP paying when you scale down."},
    {"d": 0, "term": "6 R's — Rehost", "def": "Lift-and-shift: move app to EC2 unchanged, like moving furniture to a new house."},
    {"d": 0, "term": "6 R's — Replatform", "def": "Small cloud tweaks, e.g. move MySQL on EC2 to managed RDS — same app, better plumbing."},
    {"d": 0, "term": "6 R's — Refactor", "def": "Rewrite app cloud-native — Lambda, microservices. Most work, most cloud benefit."},
    {"d": 0, "term": "6 R's — Repurchase", "def": "Dump custom app for SaaS like Salesforce — buy software instead of hosting it."},
    {"d": 0, "term": "Snowball vs DataSync", "def": "Snowball = ship a physical box of data. DataSync = automated online sync over network."},
    {"d": 0, "term": "DMS vs SCT", "def": "DMS copies live database data. SCT converts schema when changing database engine."},
    {"d": 0, "term": "Rightsizing", "def": "Pick the shoe size that fits — don't run a giant server at 5% CPU."},
    {"d": 0, "term": "BYOL", "def": "Bring Your Own License — use software licenses you already own on Dedicated Hosts."},
    # Domain 2 — Security
    {"d": 1, "term": "Shared responsibility", "def": "AWS secures the cloud (hardware). YOU secure IN the cloud (data, passwords, OS on EC2)."},
    {"d": 1, "term": "Security OF vs IN cloud", "def": "OF = AWS fixes physical servers. IN = you fix your passwords, apps, and EC2 patches."},
    {"d": 1, "term": "EC2 vs RDS responsibility", "def": "EC2: YOU patch OS. RDS: AWS patches database engine; YOU manage data and access."},
    {"d": 1, "term": "Least privilege", "def": "Give only the keys needed — guest gets one room key, not the master key to the whole hotel."},
    {"d": 1, "term": "Root user", "def": "God account from signup. Enable MFA, never use daily, never share. Only root closes account."},
    {"d": 1, "term": "IAM role vs IAM user", "def": "User = person with password. Role = temporary hat for services (Lambda, EC2) — no long-term keys."},
    {"d": 1, "term": "IAM Identity Center", "def": "Single sign-on (SSO) — one school ID opens every AWS account and app."},
    {"d": 1, "term": "MFA", "def": "Password PLUS phone code — thief needs both to break in."},
    {"d": 1, "term": "Security Group", "def": "Instance bouncer — stateful, allow-only rules. Return traffic auto-allowed."},
    {"d": 1, "term": "NACL", "def": "Subnet fence — stateless, numbered rules, can DENY specific IPs at subnet edge."},
    {"d": 1, "term": "SG vs NACL", "def": "SG = instance level, stateful, allow only. NACL = subnet level, stateless, allow AND deny."},
    {"d": 1, "term": "GuardDuty", "def": "Security guard watching your account 24/7 for hackers and weird API calls (ML-based)."},
    {"d": 1, "term": "Inspector", "def": "Doctor checking EC2 for missing patches and CVE holes — vulnerability scans."},
    {"d": 1, "term": "Macie", "def": "Detective finding credit cards and SSNs hiding in S3 buckets."},
    {"d": 1, "term": "WAF", "def": "Web bouncer blocking SQL injection and XSS at your website door (Layer 7)."},
    {"d": 1, "term": "Shield", "def": "DDoS protection — Standard is FREE for everyone. Stops traffic floods."},
    {"d": 1, "term": "TRAP: GuardDuty vs Inspector", "def": "GuardDuty = ongoing threats. Inspector = missing patches. Don't swap them on the exam!"},
    {"d": 1, "term": "TRAP: WAF vs Shield", "def": "WAF = web app attacks (SQLi). Shield = DDoS flood attacks. Different layers."},
    {"d": 1, "term": "CloudTrail", "def": "Security camera log — who called which API, when, from where."},
    {"d": 1, "term": "AWS Config", "def": "Rule checker — alerts when someone creates an unencrypted S3 bucket."},
    {"d": 1, "term": "AWS Artifact", "def": "Compliance PDF library — download SOC/PCI reports for auditors."},
    {"d": 1, "term": "Security Hub", "def": "One dashboard combining findings from GuardDuty, Inspector, and more."},
    {"d": 1, "term": "KMS", "def": "Key manager — creates encryption keys for S3, EBS, RDS."},
    {"d": 1, "term": "Secrets Manager", "def": "Password vault with auto-rotation — never hardcode DB passwords."},
    {"d": 1, "term": "ACM", "def": "Free SSL/TLS certificates for HTTPS websites — auto-renews."},
    {"d": 1, "term": "Encryption at rest vs in transit", "def": "At rest = stored data encrypted (KMS). In transit = HTTPS/TLS while data moves."},
    {"d": 1, "term": "Firewall Manager", "def": "Boss managing WAF rules across many AWS accounts at once."},
    {"d": 1, "term": "Network Firewall", "def": "VPC perimeter IDS/IPS — deep inspection at network edge."},
    # Domain 3 — Technology
    {"d": 2, "term": "Console vs CLI vs SDK", "def": "Console = click in browser. CLI = terminal commands. SDK = code in Python/Java apps."},
    {"d": 2, "term": "CloudFormation", "def": "Recipe book (JSON/YAML) that builds identical AWS setups every time — Infrastructure as Code."},
    {"d": 2, "term": "EC2 On-Demand", "def": "Pay by the hour, no contract — best for unpredictable or short jobs."},
    {"d": 2, "term": "Reserved / Savings Plans", "def": "Commit 1–3 years, save up to ~72% — best for steady 24/7 servers."},
    {"d": 2, "term": "Spot Instances", "def": "Up to 90% off spare capacity — AWS can take them back with 2 min warning."},
    {"d": 2, "term": "Dedicated Hosts", "def": "Whole physical server for you — needed for BYOL license rules."},
    {"d": 2, "term": "Lambda", "def": "Run code when something happens — pay per millisecond, zero servers to manage."},
    {"d": 2, "term": "ECS vs EKS", "def": "ECS = AWS containers, simpler. EKS = Kubernetes containers, industry standard."},
    {"d": 2, "term": "Fargate", "def": "Run containers without managing EC2 — tell AWS CPU/RAM, it runs the box."},
    {"d": 2, "term": "TRAP: Lambda vs EC2", "def": "Lambda = short event jobs, no server. EC2 = full control, you manage OS. Batch video render might be Spot EC2, not Lambda."},
    {"d": 2, "term": "Auto Scaling", "def": "Robot manager adding/removing EC2 when CPU or traffic changes."},
    {"d": 2, "term": "ELB / ALB", "def": "Traffic cop spreading requests across healthy EC2 instances in multiple AZs."},
    {"d": 2, "term": "S3", "def": "Unlimited file bucket in the cloud — photos, backups, static websites."},
    {"d": 2, "term": "EBS", "def": "One EC2's hard drive — block storage, persists after reboot."},
    {"d": 2, "term": "EFS", "def": "Shared folder many EC2s mount at once — like a network drive."},
    {"d": 2, "term": "S3 vs EBS vs EFS", "def": "S3 = files via HTTP. EBS = one disk on one EC2. EFS = shared NFS for many EC2s."},
    {"d": 2, "term": "Instance store", "def": "Super fast TEMP disk on EC2 — data gone when instance stops. Not EBS!"},
    {"d": 2, "term": "Glacier Deep Archive", "def": "Cheapest storage — retrieve in hours. For 7-year legal archives."},
    {"d": 2, "term": "FSx", "def": "Managed Windows or Lustre file shares — SMB for Windows shops."},
    {"d": 2, "term": "Storage Gateway", "def": "Bridge — on-prem apps think they're using local storage but it's backed by AWS."},
    {"d": 2, "term": "RDS vs DynamoDB", "def": "RDS = SQL tables, relationships. DynamoDB = NoSQL, massive scale, milliseconds."},
    {"d": 2, "term": "Aurora", "def": "AWS supercharged MySQL/PostgreSQL — faster, auto-replicates across 3 AZs."},
    {"d": 2, "term": "ElastiCache", "def": "Super-fast memory cache — stop hitting the database for same data repeatedly."},
    {"d": 2, "term": "Redshift", "def": "Giant spreadsheet in the sky — analytics on petabytes of data."},
    {"d": 2, "term": "VPC", "def": "Your private neighborhood in AWS — subnets, routes, gateways."},
    {"d": 2, "term": "Public vs private subnet", "def": "Public = route to internet (web servers). Private = no direct internet (databases)."},
    {"d": 2, "term": "Route 53", "def": "Phone book of the internet — turns myapp.com into IP addresses + health checks."},
    {"d": 2, "term": "CloudFront", "def": "CDN — copies your content to edge locations worldwide for fast delivery."},
    {"d": 2, "term": "VPN vs Direct Connect", "def": "VPN = encrypted tunnel over internet. Direct Connect = private dedicated line to AWS."},
    {"d": 2, "term": "CloudWatch", "def": "Dashboard + alarms for CPU, logs, and app health."},
    {"d": 2, "term": "Systems Manager", "def": "Patch and manage hundreds of EC2 instances from one console."},
    {"d": 2, "term": "TRAP: CloudWatch vs CloudTrail", "def": "CloudWatch = performance metrics. CloudTrail = who did what API call. Totally different!"},
    {"d": 2, "term": "SageMaker", "def": "Build and train machine learning models."},
    {"d": 2, "term": "Lex", "def": "Chatbot that understands speech — powers Alexa-style menus."},
    {"d": 2, "term": "Athena", "def": "SQL queries on files in S3 — no database server needed."},
    {"d": 2, "term": "Kinesis", "def": "Firehose of live data — clicks, IoT sensors, streams in real time."},
    {"d": 2, "term": "SQS vs SNS", "def": "SQS = queue, one worker pulls jobs. SNS = megaphone, fans out to many listeners."},
    {"d": 2, "term": "EventBridge", "def": "Event router — when X happens, trigger Y (email, Lambda, etc.)."},
    {"d": 2, "term": "WorkSpaces vs AppStream", "def": "WorkSpaces = full virtual desktop. AppStream = stream one heavy app to browser."},
    # Domain 4 — Billing
    {"d": 3, "term": "Cost Explorer", "def": "Look at PAST bills — charts of what you already spent."},
    {"d": 3, "term": "AWS Budgets", "def": "Alarm when spending hits a limit — email at 80% and 100%."},
    {"d": 3, "term": "Pricing Calculator", "def": "Estimate FUTURE costs before you build anything."},
    {"d": 3, "term": "TRAP: Cost Explorer vs Budgets vs Calculator", "def": "Explorer=past. Budgets=alerts. Calculator=before deploy. Top exam trick!"},
    {"d": 3, "term": "Organizations", "def": "Parent account managing many child accounts — one bill, shared discounts."},
    {"d": 3, "term": "SCPs", "def": "Company rules even admins cannot break — e.g. 'no one launches in eu-west-1'."},
    {"d": 3, "term": "Consolidated billing", "def": "All team AWS accounts on one monthly invoice."},
    {"d": 3, "term": "Cost allocation tags", "def": "Labels on resources so finance sees which team spent what."},
    {"d": 3, "term": "CUR", "def": "Cost and Usage Report — raw detailed billing export for spreadsheets."},
    {"d": 3, "term": "Basic Support", "def": "Free — docs and forums only. NO 24/7 phone."},
    {"d": 3, "term": "Developer Support", "def": "Business-hours email support — solo devs."},
    {"d": 3, "term": "Business Support", "def": "24/7 phone/chat + full Trusted Advisor."},
    {"d": 3, "term": "Enterprise Support", "def": "Dedicated TAM (your personal AWS expert) + concierge."},
    {"d": 3, "term": "Enterprise On-Ramp", "def": "Bridge plan — pool of TAM access before full Enterprise."},
    {"d": 3, "term": "Trusted Advisor", "def": "Free robot advisor — flags open ports, idle servers, missing backups."},
    {"d": 3, "term": "Health Dashboard", "def": "Alerts when AWS problems affect YOUR specific resources."},
    {"d": 3, "term": "Inbound data transfer", "def": "Uploading TO AWS from internet — usually FREE."},
    {"d": 3, "term": "Outbound / cross-Region transfer", "def": "Sending data OUT of AWS or to another Region — costs money."},
]
